---
# tasks file for roles/install_ohmyposh
- name: Remove scripts directory
  ansible.builtin.file:
    state: absent
    path: "{{ ohmyposh_script_dir }}"
  ignore_errors: true

- name: Remove themes directory
  ansible.builtin.file:
    state: absent
    path: "{{ ohmyposh_themes_dir }}"
  ignore_errors: true

- ansible.builtin.file:
    state: directory
    path: "{{ ohmyposh_script_dir }}"
    mode: "0775"
- ansible.builtin.file:
    state: directory
    path: "{{ ohmyposh_themes_dir }}"
    mode: "0775"

- name: Change script and themes permissions
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "chmod -R 775 {{ ohmyposh_script_dir }}"
    - "chmod -R 775 {{ ohmyposh_themes_dir }}"

- name: Download oh-my-posh
  ansible.builtin.get_url:
    url: https://ohmyposh.dev/install.sh
    validate_certs: false
    dest: "{{ ohmyposh_script_dir }}/install.sh"

# - name: Download oh-my-posh themes
#   ansible.builtin.get_url:
#     url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip
#     dest: "{{ ohmyposh_themes_dir }}"
#     force: true

- name: Download oh-my-posh themes
  ansible.builtin.include_role:
    name: download_github_asset
  vars:
    download_github_asset_owner: JanDeDobbeleer
    download_github_asset_repo: oh-my-posh
    download_github_asset_filename: themes.zip
    download_github_asset_dest: "{{ ohmyposh_themes_dir }}"
    download_github_asset_github_token: "{{ github_api_token_eget | default(github_api_token_debget) | default('') }}"

- name: Rename themes file
  ansible.builtin.command: "mv {{ ohmyposh_themes_dir }}/themes.zip {{ ohmyposh_themes_dir }}/themes.zip.gz"
- name: Change themes permissions
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "chmod -R 775 {{ ohmyposh_themes_dir }}"

- name: Unzip themes by two ways
  block:
    - name: Unzip oh-my-posh themes by built-in unarchive module
      ansible.builtin.unarchive:
        src: "{{ ohmyposh_themes_dir }}/themes.zip.gz"
        dest: "{{ ohmyposh_themes_dir }}"
  rescue:
    - name: Unzip oh-my-posh themes by shell module with unzip tool
      ansible.builtin.command: "unzip -o {{ ohmyposh_themes_dir }}/themes.zip.gz -d {{ ohmyposh_themes_dir }}"
- name: Change themes permissions
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "chmod -R 775 {{ ohmyposh_themes_dir }}"

- name: Remove themes archive
  ansible.builtin.file:
    state: absent
    path: "{{ ohmyposh_themes_dir }}/themes.zip.gz"

- name: Change script permissions
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "chmod -R 775 {{ ohmyposh_script_dir }}"

- name: Install oh-my-posh
  ansible.builtin.command: "{{ ohmyposh_script_dir }}/install.sh -d /usr/local/bin"
  args:
    creates: "/root/usr/bin/oh-my-posh"

- name: Install Nerd fonts
  ansible.builtin.command: "oh-my-posh font install CascadiaCode"
- name: Ensure that profile exists
  ansible.builtin.file:
    path: "{{ ohmyposh_project_fullpath }}/.bashrc"
    state: touch

- name: Remove oh-my-posh obsolete line from .profile
  ansible.builtin.lineinfile:
    path: "{{ ohmyposh_project_fullpath }}/.profile"
    regexp: eval\s\"\$\(oh-my-posh.+
    state: absent
    backup: true
  ignore_errors: true

- name: Remove oh-my-posh obsolete line from Bash profile
  ansible.builtin.lineinfile:
    path: "{{ ohmyposh_project_fullpath }}/.bashrc"
    regexp: eval\s\"\$\(oh-my-posh.+
    state: absent
    backup: true

- name: Add oh-my-posh to Bash profile
  ansible.builtin.lineinfile:
    path: "{{ ohmyposh_project_fullpath }}/.bashrc"
    line: "eval \"$(oh-my-posh init bash --config {{ ohmyposh_themes_dir }}/{{ ohmyposh_theme }}.omp.json)\""

- name: Remove scripts directory
  ansible.builtin.file:
    state: absent
    path: "{{ ohmyposh_script_dir }}"
  ignore_errors: true
