---
# tasks file for roles/install_ohmyposh
  - name: Remove scripts directory
    file:
      state: absent
      path: "{{ ohmyposh_script_dir }}"
    ignore_errors: yes

  - name: Remove themes directory
    file:
      state: absent
      path: "{{ ohmyposh_themes_dir }}"
    ignore_errors: yes

  - file:
      state: directory
      path: "{{ ohmyposh_script_dir }}"
      mode: 0775
  - file:
      state: directory
      path: "{{ ohmyposh_themes_dir }}"
      mode: 0775
  
  - name: Change script and themes permissions
    command: "{{ item }}"
    with_items: 
    - "chmod -R 775 {{ ohmyposh_script_dir }}"
    - "chmod -R 775 {{ ohmyposh_themes_dir }}"

  - name: Download oh-my-posh
    get_url:
      url: https://ohmyposh.dev/install.sh
      validate_certs: false
      dest: "{{ ohmyposh_script_dir }}/install.sh"

  - name: Download oh-my-posh themes
    get_url:
      url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip
      dest: "{{ ohmyposh_themes_dir }}"
      force: true

  - name: Rename themes file
    shell: "mv {{ ohmyposh_themes_dir }}/themes.zip {{ ohmyposh_themes_dir }}/themes.zip.gz"  
  
  - name: Change themes permissions
    command: "{{ item }}"
    with_items: 
    - "chmod -R 775 {{ ohmyposh_themes_dir }}"

  - name: Unzip themes by two ways
    block:
      - name: Unzip oh-my-posh themes by built-in unarchive module
        unarchive:
          src: "{{ ohmyposh_themes_dir }}/themes.zip.gz"
          dest: "{{ ohmyposh_themes_dir }}"
    rescue:
      - name: Unzip oh-my-posh themes by shell module with unzip tool
        shell: "unzip -o {{ ohmyposh_themes_dir }}/themes.zip.gz -d {{ ohmyposh_themes_dir }}"

  - name: Change themes permissions
    command: "{{ item }}"
    with_items: 
    - "chmod -R 775 {{ ohmyposh_themes_dir }}"

  - name: Remove themes archive
    file:
      state: absent
      path: "{{ ohmyposh_themes_dir }}/themes.zip.gz"

  - name: Change script permissions
    command: "{{ item }}"
    with_items: 
    - "chmod -R 775 {{ ohmyposh_script_dir }}"

  - name: Install oh-my-posh
    command: "{{ ohmyposh_script_dir }}/install.sh -d /usr/local/bin"
    args:
      creates: "/root/usr/bin/oh-my-posh"

  - name: Install Nerd fonts
    command: "oh-my-posh font install CascadiaCode"

  - name: Ensure that profile exists
    file:
      path: "{{ ohmyposh_project_fullpath }}/.profile"
      state: touch

  - name: Remove oh-my-posh obsolete line from profile
    lineinfile:
      path: "{{ ohmyposh_project_fullpath }}/.profile"
      regexp: eval\s\"\$\(oh-my-posh.+
      state: absent
      backup: yes

  - name: Add oh-my-posh to profile
    lineinfile:
      path: "{{ ohmyposh_project_fullpath }}/.profile"
      line: "eval \"$(oh-my-posh init bash --config {{ ohmyposh_themes_dir }}/{{ ohmyposh_theme }}.omp.json)\""

  - name: Remove scripts directory
    file:
      state: absent
      path: "{{ ohmyposh_script_dir }}"
    ignore_errors: yes