version: "3.8"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6
    container_name: nginx-proxy
    cpus: "0.5"
    mem_limit: 200m
    env_file:
      - .env
    networks:
      - caddy-fallback
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./config/vhost.d:/etc/nginx/vhost.d:ro
      # - type: bind
      #   source: ./config/root/my_proxy.conf
      #   target: /etc/nginx/conf.d/my_proxy.conf
      #   read_only: true
      # - ./static:/var/www/html

networks:
  caddy-fallback:
    external: true