version: "3.8"

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    cpus: "0.5"
    mem_limit: 200m
    networks:
      - xui_network
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/usr/share/nginx/html:ro
    restart: unless-stopped

networks:
  xui_network:
    external: true