# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/install_deb_mirrors
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Validate country code
  ansible.builtin.assert:
    that:
      - country_code is match('^[a-z]{2}$')
    fail_msg: >-
      Invalid country code "{{ country_code }}" in
      inventory hostname "{{ inventory_hostname }}".
      Expected exactly two lowercase letters.

- name: Ensure python3-debian is installed
  ansible.builtin.apt:
    name: python3-debian
    state: present

- name: Create APT mirror list
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/ubuntu-mirrors.txt
    owner: root
    group: root
    mode: "0644"
    content: |
      {% for mirror in deb_mirrors %}
      {{ mirror.url }}
      {% endfor %}
  register: deb_mirror_list
  when:
    - country_code_upper
        in deb_mirrors_country_code_allowlist
    - ansible_facts['distribution'] == "Ubuntu"

- name: Configure Ubuntu mirror list
  become: true
  ansible.builtin.deb822_repository:
    name: ubuntu-mirror-list
    types:
      - deb
    uris:
      - mirror+file:/etc/apt/ubuntu-mirrors.txt
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
      - "{{ ansible_facts['distribution_release'] }}-updates"
      - "{{ ansible_facts['distribution_release'] }}-backports"
      - "{{ ansible_facts['distribution_release'] }}-security"
    components:
      - main
      - restricted
      - universe
      - multiverse
    signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg
    state: present
  register: deb_mirror_repository
  when:
    - country_code_upper
        in deb_mirrors_country_code_allowlist
    - ansible_facts['distribution'] == "Ubuntu"


- name: Configure Debian repositories
  become: true
  ansible.builtin.deb822_repository:
    name: debian
    types:
      - deb
    uris:
      - https://deb.debian.org/debian
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
      - "{{ ansible_facts['distribution_release'] }}-updates"
      - "{{ ansible_facts['distribution_release'] }}-backports"
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    state: present
  register: debian_repository
  when:
    - ansible_facts['distribution'] == "Debian"


- name: Configure Debian security repository
  become: true
  ansible.builtin.deb822_repository:
    name: debian-security
    types:
      - deb
    uris:
      - https://security.debian.org/debian-security
    suites:
      - "{{ ansible_facts['distribution_release'] }}-security"
    components:
      - main
      - contrib
      - non-free
      - non-free-firmware
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
    state: present
  register: debian_security_repository
  when:
    - ansible_facts['distribution'] == "Debian"


- name: Remove Ubuntu mirror repository from Debian
  become: true
  ansible.builtin.deb822_repository:
    name: ubuntu-mirror-list
    state: absent
  when:
    - ansible_facts['distribution'] == "Debian"


- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  when:
    - >
      (deb_mirror_repository is defined and deb_mirror_repository is changed)
      or
      (debian_repository is defined and debian_repository is changed)
      or
      (debian_security_repository is defined and debian_security_repository is changed)

- name: Update APT cache
  become: true
  ansible.builtin.apt:
    update_cache: true
  when:
    - country_code_upper
        in deb_mirrors_country_code_allowlist
    - deb_mirror_list.changed or deb_mirror_repository.changed
