---
# tasks file for roles/remove_ufw_rules

- name: Check if UFW is installed
  ansible.builtin.command: dpkg -l | grep ufw
  register: ufw_installed
  changed_when: false
  failed_when: false

- name: Check if UFW is enabled
  ansible.builtin.command: ufw status
  register: ufw_status
  changed_when: false
  failed_when: false
  when: ufw_installed.stdout != ""

- name: Set fact that UFW is (not) enabled
  ansible.builtin.set_fact:
    ufw_enabled: "{{ 'inactive' not in ufw_status.stdout }}"
  when: ufw_installed.stdout != ""

- name: Delete rule in UFW (for TCP)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    delete: true
  loop: "{{ ufw_ports }}"
  when:
    - ufw_installed.stdout != ""
    - ufw_enabled
    - input_mode is not defined or input_mode == 'list'
    - "'tcp' in ufw_protos"
- name: Delete rule in UFW (for UDP)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
    delete: true
  loop: "{{ ufw_ports }}"
  when:
    - ufw_installed.stdout != ""
    - ufw_enabled
    - input_mode is not defined or input_mode == 'list'
    - "'tcp' in ufw_protos"
