---
- name: Install and configure Telegram bots from Bedolaga for Remnawave panel
  hosts: vpn_server_remnawave
  become: false
  become_user: "{{ standard_user }}"

  roles:
    - name: kwtoolset/resolve_host_relations
      vars:
        resolve_host_relations_group: vpn_server_remnawave
        resolve_host_relations_component: tgbot_bedolaga
    - install_vpn_server_remnawave_tgbot_bedolaga
