---
- name: Install web features - currently includes certcopy only
  hosts: vpn_caddy:vpn_remna_server_caddy:analytics_node
  become: false
  become_user: "{{ standard_user }}"

  roles:
    - name: kwtoolset/resolve_host_relations
      vars:
        resolve_host_relations_group: webfeatures
        resolve_host_relations_component: certcopy
    - install_webfeatures_certcopy