---
- name: Generate Remnawave hosts
  hosts: vpn_server_remnawave
  become: false
  become_user: "{{ standard_user }}"
  gather_facts: false
  vars:
    vpn_server_remnawave_generate_stages:
      - hosts

  roles:
    - name: kwtoolset/resolve_host_relations
      vars:
        resolve_host_relations_group: vpn_server_remnawave
        resolve_host_relations_component: panel
    - configure_remnawave_panel_generate_setup
