---
# tasks file for roles/kwtoolset/collect_ports
- name: Check if {{ files_path }} directory exists
  ansible.builtin.stat:
    path: "{{ files_path }}"
  register: files_path_stat
  failed_when:
    - files_path_stat.stat.exists == false 
    - skip_if_not_found == false
  
- name: Find all .env files recursively in the {{ files_path }} directory
  ansible.builtin.find:
    paths: "{{ files_path }}"
    patterns: "{{ filename_pattern }}"
    recurse: yes
    hidden: yes
  register: found_files
  when: files_path_stat.stat.exists == true
- name: Extract PORT values from .env files
  ansible.builtin.shell: "grep -E '^[A-Za-z_]+{{ substring_pattern }}[[:space:]]*=[[:space:]]*[0-9]+' {{ item.path }} | awk -F '=' '{print $2}' | tr -d ' '"
  loop: "{{ found_files.files }}"
  loop_control:
    loop_var: item
  register: ports_from_file
  when: files_path_stat.stat.exists == true
- name: Collect PORT values into a list
  set_fact:
    collected_ports: "{{ (ports_from_file.results | selectattr('stdout', 'defined') | map(attribute='stdout_lines') | flatten | map('int')) | unique }}"
  when: files_path_stat.stat.exists == true

