---
# tasks file for roles/install_analytics_node_fail2ban_exporter

- name: Capture this role's path so nested role can use the parent role_path
  ansible.builtin.set_fact:
    this_role_path: "{{ role_path }}"
  tags:
    - always

- name: Add to source_paths the current role templates directory
  ansible.builtin.set_fact:
    source_paths: >-
      {{
        (
            source_paths_add_role_dirs
            | default([])
            | map('regex_replace', '^(.*)$', this_role_path ~ '/\1/')
            | list
          )
        + (source_paths_add_repo_dirs | default([]))
        + (source_paths_add_user_dirs | default([]))
      }}
  tags:
    - always

# Fail2Ban existence Check
- name: Check if Fail2Ban is installed
  ansible.builtin.command: "fail2ban-client -V"
  register: fail2ban_installed
  ignore_errors: true
- name: Fail if Fail2Ban is not installed
  ansible.builtin.fail:
    msg: "Fail2Ban is not installed on this host."
  when: fail2ban_installed.rc != 0
- name: Check if Fail2Ban is running
  ansible.builtin.systemd:
    name: fail2ban
    state: started
  register: fail2ban_running
  ignore_errors: true
- name: Fail if Fail2Ban is not running
  ansible.builtin.fail:
    msg: "Fail2Ban is not running on this host."
  when: fail2ban_running.failed

# Docker network
- name: Ensure Docker network {{ analytics_node_network_name }} exists with specific settings
  community.docker.docker_network:
    name: "{{ analytics_node_network_name }}"
    driver: bridge
    state: present

- name: container_stop_down
  ansible.builtin.include_role:
    name: kwtoolset/container_stop_down
    apply:
      tags:
        - update_image
        - update_config
  vars:
    container_stop_down_list:
      - "{{ dest_path_full }}"
    docker_compose_project_name_list:
      - "{{ compose_project_name }}"
      - "{{ project_dir }}"
  tags:
    - update_image
    - update_config
- name: copy_files_templating
  ansible.builtin.include_role:
    name: kwtoolset/copy_files_templating
    apply:
      tags:
        - update_config
  vars:
    copy_files_templating_dir_list:
      - src: "{{ source_path }}"
        dest: "{{ dest_path_full }}"
        default_mode: "0775"
  with_items: "{{ source_paths }}"
  loop_control:
    loop_var: source_path
  tags:
    - update_config
- name: container_pull
  ansible.builtin.include_role:
    name: kwtoolset/container_pull
    apply:
      tags:
        - update_image
  vars:
    container_pull_list:
      - path: "{{ dest_path_full }}"
        name: "{{ compose_project_name }}"
        policy: "policy"
  tags:
    - update_image
- name: container_up
  ansible.builtin.include_role:
    name: kwtoolset/container_up
    apply:
      tags:
        - update_image
        - update_config
  vars:
    container_up_list:
      - path: "{{ dest_path_full }}"
        name: "{{ compose_project_name }}"
        ignore_errors: false
  tags:
    - update_image
    - update_config

- name: Add port {{ fail2ban_exporter_external_port }} to UFW
  become: true
  become_user: root
  community.general.ufw:
    rule: allow
    port: "{{ fail2ban_exporter_external_port }}"
    proto: tcp
  when:
    - fail2ban_exporter_external_port is defined
    - fail2ban_exporter_external_port | length > 0
