---
- name: Install packages by eget
  hosts: general_vps_prepare
  become: true

  environment:
    EGET_GITHUB_TOKEN: "{{ github_api_token_eget | default(omit) }}"

  roles:
    - name: ./roles/install_packages_binary
