---
- name: Disable password authentication
  hosts: all
  become: true
  become_user: root
  roles:
    - devsec.hardening.ssh_hardening

  pre_tasks:
    - name: Check if SSH keys are present
      ansible.builtin.stat:
        path: "/home/{{ standard_user }}/.ssh/authorized_keys"
      register: ssh_keys

    - name: Fail if no SSH keys are present
      ansible.builtin.fail:
        msg: "No SSH keys found in /home/{{ standard_user }}/.ssh/authorized_keys. Aborting to prevent lockout."
      when:
        - not ssh_keys.stat.exists or ssh_keys.stat.size < 100

    - name: Check if user is in the list of allowed users - {{ standard_user }}
      ansible.builtin.debug:
        msg: "User {{ standard_user }} is in the list of allowed users"
      when:
        - standard_user in ssh_allow_users
        - ssh_allow_users is defined

    - name: Fail if user is not in the list of allowed users - {{ standard_user }}
      ansible.builtin.fail:
        msg: "User {{ standard_user }} is not in the list of allowed users. Aborting to prevent lockout."
      when:
        - standard_user not in ssh_allow_users
        - ssh_allow_users is defined

    - name: Display caution message
      ansible.builtin.debug:
        msg: "⚠️ Caution❗❗❗ This will limit SSH connection to a specific list of users: {{ ssh_allow_users }}"
      when: ssh_allow_users is defined

    - name: Delay 10s before proceeding
      ansible.builtin.wait_for:
        timeout: 10
      when: ssh_allow_users
