---
- name: Setup Bash profile
  hosts: general_vps_prepare
  become: true

  pre_tasks:
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: _bash_profile
      register: bash_profile_temp_dir
    - name: Template bash profile files to temporary directory
      ansible.builtin.template:
        src: "{{ bash_asset_fullpath }}/.bashrc.j2"
        dest: "{{ bash_profile_temp_dir.path }}/.bashrc"
    
  tasks:
    - name: Apply text_from_file role
      ansible.builtin.include_role:
        name: ./roles/kwtoolset/text_from_file
      vars:
        text_from_file_source_file_path: "{{ bash_profile_temp_dir.path }}/.bashrc"
        text_from_file_dest_file_path: "/home/{{ standard_user }}/.bashrc"
        text_from_file_dest_file_path_mode: "0644"
        text_from_file_remove_blocks:
          - "{{ bash_profile_marker_legacy }}"
        text_from_file_remove_specific_lines_regex:
          - "alias\\sbr(\\s)?="
        text_from_file_append_lines:
          - "eval \"$(oh-my-posh init bash --config {{ ohmyposh_themes_dir }}/{{ ohmyposh_theme.bash | default(ohmyposh_theme.default) }}.omp.json)\""
  
  post_tasks:
    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ bash_profile_temp_dir.path }}"
        state: absent