---
- name: Setup PowerShell profile
  hosts: general_vps_prepare
  become: true

  pre_tasks:
    - name: Get Powershell executable path
      ansible.builtin.shell: "command -v pwsh"
      register: pwsh_path
    - name: Get Powershell $PROFILE path
      become: true
      become_user: "{{ standard_user }}"
      ansible.builtin.shell: $PROFILE
      args:
        executable: "{{ pwsh_path.stdout }}"
      register: pwsh_profile
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: _pwsh_profile
      register: pwsh_profile_temp_dir
    - name: Template pwsh profile files to temporary directory
      ansible.builtin.template:
        src: "{{ powershell_asset_fullpath }}/Microsoft.PowerShell_profile.ps1.j2"
        dest: "{{ pwsh_profile_temp_dir.path }}/Microsoft.PowerShell_profile.ps1"
  
  tasks:
    - name: Apply text_from_file role
      ansible.builtin.include_role:
        name: ./roles/kwtoolset/text_from_file
      vars:
        text_from_file_source_file_path: "{{ pwsh_profile_temp_dir.path }}/Microsoft.PowerShell_profile.ps1"
        text_from_file_dest_file_path: "{{ pwsh_profile.stdout }}"
        text_from_file_dest_file_path_mode: "0644"
        text_from_file_remove_lines_to_EOF:
          - ".*posh-git"
          - ".*PSReadLine"
  
  post_tasks:
    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ pwsh_profile_temp_dir.path }}"
        state: absent
    - name: Change .config owner and group
      ansible.builtin.command: "chown -R {{ standard_user }}:{{ standard_user }} {{ ohmyposh_powershell_project_fullpath }}/.config"
    - name: Change .config permissions
      ansible.builtin.command: "chmod -R 775 {{ ohmyposh_powershell_project_fullpath }}/.config"
