---
- name: Install packages by deb-get
  hosts: general_vps_prepare
  become: true

  environment:
    DEBGET_TOKEN: "{{ github_api_token_debget | default(omit) }}"

  roles:
    - name: ./roles/install_packages_deb
