---
- name: Configure configs for doas
  hosts: general_vps_prepare
  become: true
  become_user: root

  vars:
    project_dir: doas
    project_root_dir: "{{ general_vps_prepare_project_structure_root }}"
    source_asset_rootpath_common: "{{ playbook_dir }}/assets/hosts-list/common/{{ project_root_dir }}"
    source_asset_fullpath_common: "{{ source_asset_rootpath_common }}/{{ project_dir }}"
    source_asset_rootpath_project: "{{ playbook_dir }}/assets/hosts-list/{{ inventory_hostname }}/{{ project_root_dir }}"
    source_asset_fullpath_project: "{{ source_asset_rootpath_project }}/{{ project_dir }}"
    dest_project_rootpath: "/etc"
    
  tasks:
    - name: Copy doas.conf from common assets
      become: true
      become_user: root
      ansible.builtin.template:
        src: "{{ source_asset_fullpath_common }}/doas.conf.j2"
        dest: "{{ dest_project_rootpath }}/doas.conf"
        owner: root
        group: root
        mode: "0600"
    - name: Copy doas.conf from project assets
      become: true
      become_user: root
      ansible.builtin.template:
        src: "{{ source_asset_fullpath_project }}/doas.conf.j2"
        dest: "{{ dest_project_rootpath }}/doas.conf"
        owner: root
        group: root
        mode: "0600"
      ignore_errors: true

    - name: Grant user {{ standard_user }} read and write access to a file
      become: true
      become_user: root
      ansible.posix.acl:
        path: /etc/doas.conf
        entity: "{{ standard_user }}"
        etype: user
        permissions: rw
        state: present

    - name: Ensure doas.conf has 0600 permissions
      become: true
      become_user: root
      ansible.builtin.file:
        path: /etc/doas.conf
        mode: "0600"
        state: file
