---
- name: Setup Bash profile
  hosts: general_vps_prepare
  become: true

  roles:
    - name: ./roles/kwtoolset/lines_from_file
      vars:
        lines_from_file_source_file_path: "{{ bash_asset_fullpath }}/.bashrc"
        lines_from_file_dest_file_path: "/home/{{ standard_user }}/.bashrc"
        lines_from_file_dest_file_path_mode: "0644"
        lines_from_file_remove_lines_regex:
          - "alias\\sbr(\\s)?="
        lines_from_file_append_lines:
          - "eval \"$(oh-my-posh init bash --config {{ ohmyposh_themes_dir }}/{{ ohmyposh_theme }}.omp.json)\""
