---
- name: Configure configs of various tools (like doas)
  hosts: general_vps_prepare
  become: true
  become_user: root

  roles:
    - name: ./roles/kwtoolset/copy_files_templating
      vars:
        project_dir: doas
        project_name: doas
        project_root_dir: "{{ general_vps_prepare_project_structure_root }}"
        source_asset_rootpath_common: "{{ playbook_dir }}/assets/hosts-list/common/{{ project_root_dir }}"
        source_asset_fullpath_common: "{{ source_asset_rootpath_common }}/{{ project_dir }}"
        source_asset_rootpath_project: "{{ playbook_dir }}/assets/hosts-list/{{ inventory_hostname }}/{{ project_root_dir }}"
        source_asset_fullpath_project: "{{ source_asset_rootpath_project }}/{{ project_dir }}"
        dest_project_rootpath: "/etc"
        copy_files_templating_dir_list:
          - src: "{{ source_asset_fullpath_common }}/"
            dest: "{{ dest_project_rootpath }}"
            default_mode: "0600"
          - src: "{{ source_asset_fullpath_project }}/"
            dest: "{{ dest_project_rootpath }}"
            default_mode: "0600"
    
  post_tasks:
    - name: Grant user {{ standard_user }} read and write access to a file
      become: true
      become_user: root
      ansible.posix.acl:
        path: /etc/doas.conf
        entity: "{{ standard_user }}"
        etype: user
        permissions: rw
        state: present

    - name: Ensure doas.conf has 0600 permissions
      become: true
      become_user: root
      ansible.builtin.file:
        path: /etc/doas.conf
        mode: "0600"
        state: file
