---
- name: Add SSH ports to sshd_config
  hosts: all
  become: true
  become_user: root

  roles:
    - name: roles/kwtoolset/append_lines
      vars:
        append_lines_dest_file_path: "{{ sshd_config_file_location }}"
        append_lines_list: "{{ ssh_ports_to_add }}"

  post_tasks:
    - name: Ensure SSH service is restarted safely
      block:
        - name: Restart SSH service
          ansible.builtin.service:
            name: ssh
            state: restarted

        - name: Pause to allow SSH to restart
          ansible.builtin.pause:
            seconds: 5

        - name: Reset Ansible connection after SSH restart
          meta: reset_connection
      rescue:
        - name: Fallback message if SSH restart fails
          debug:
            msg: "Failed to restart SSH. Ensure the service is configured properly."
