---
- name: Check if group_vars/all/z_common_hosts_secrets exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/group_vars/all/z_common_hosts_secrets"
  register: initial_configure_groupvars_all_secrets_dir
  delegate_to: localhost

- name: Create group_vars/all/z_common_hosts_secrets if it does not exist
  ansible.builtin.file:
    path: "{{ playbook_dir }}/group_vars/all/z_common_hosts_secrets"
    state: directory
  when: not initial_configure_groupvars_all_secrets_dir.stat.exists
  delegate_to: localhost

- name: Ensure group_vars/all/z_common_hosts_secrets directory is empty or only contains .gitkeep file
  block:
    - name: Find all files except .gitkeep
      ansible.builtin.find:
        paths: "{{ playbook_dir }}/group_vars/all/z_common_hosts_secrets"
        file_type: file
        excludes: .gitkeep
      register: initial_configure_unwanted
      delegate_to: localhost

    - name: Prompt user if unwanted files are found
      ansible.builtin.pause:
        prompt: "❗DANGER❗ This will replace ALL YOUR SECRETS from group_vars/all/z_common_hosts_secrets directory. Make sure you made a backup if they are important. Do you want to delete them? Type exactly yes to confirm, all other values will be considered no."
      register: initial_configure_remove_unwanted_files
      when: initial_configure_unwanted.matched > 0

- name: Copy templated files for this bot instance
  ansible.builtin.include_role:
    name: kwtoolset/copy_files_templating
  vars:
    copy_files_templating_dir_list:
      - src: "{{ playbook_dir }}/templates/initial_configure/group_vars/all/z_common_hosts_secrets"
        dest: "{{ playbook_dir }}/group_vars/all"
        default_mode: "0775"
  when: (initial_configure_remove_unwanted_files.user_input is defined and initial_configure_remove_unwanted_files.user_input == 'yes') or (initial_configure_unwanted is defined and initial_configure_unwanted.matched == 0)
