---
- name: Configure X-UI database
  hosts: all
  become: false
  become_user: "{{ standard_user }}"
  vars:
    project_dir: xui_configure
    project_dir_xui: xui
    project_name: xui_configure
    project_name_xui: xui
    project_root_dir: "{{ vpn_project_structure_root }}"
    source_asset_rootpath_common: "{{ playbook_dir }}/assets/hosts-list/common/{{ project_root_dir }}"
    source_asset_fullpath_common: "{{ source_asset_rootpath_common }}/{{ project_dir }}"
    source_asset_rootpath_project: "{{ playbook_dir }}/assets/hosts-list/{{ inventory_hostname }}/{{ project_root_dir }}"
    source_asset_fullpath_project: "{{ source_asset_rootpath_project }}/{{ project_dir }}"
    dest_project_rootpath: "/home/{{ standard_user }}/{{ project_root_dir }}"
    dest_project_fullpath: "{{ dest_project_rootpath }}/{{ project_dir_xui }}"
  
  roles:
    - name: ./roles/kwtoolset/container_stop_down
      vars:
        container_stop_down_list:
          - "{{ dest_project_fullpath }}"
    - name : ./roles/vpn_xui_first_xui_configure
      vars:
        configuredb_file_name: configuredb
        base_file_names:
          - configureinbound_SS-2022_settings
          - configureinbound_SS-2022_streamsettings
          - configureinbound_VLESS_settings
          - configureinbound_VLESS_streamsettings
          - configureinbound_WG_settings
    - name: ./roles/kwtoolset/container_pull
      vars:
        container_pull_list:
          - path: "{{ dest_project_fullpath }}"
            name: "{{ project_name_xui }}"
            policy: "policy"
    - name: ./roles/kwtoolset/container_up
      vars:
        container_up_list:
          - path: "{{ dest_project_fullpath }}"
            name: "{{ project_name_xui }}"