---
- name: Install and configure Docker exporter with dependencies
  hosts: analytics_node
  become: false
  become_user: "{{ standard_user }}"
  vars:
    project_dir: docker_exporter
    docker_compose_project_name: docker_exporter
    project_root_dir: "{{ analytics_node_project_structure_root }}"
    source_asset_rootpath_common: "{{ playbook_dir }}/assets/hosts-list/common/{{ project_root_dir }}"
    source_asset_fullpath_common: "{{ source_asset_rootpath_common }}/{{ project_dir }}"
    source_asset_rootpath_project: "{{ playbook_dir }}/assets/hosts-list/{{ inventory_hostname }}/{{ project_root_dir }}"
    source_asset_fullpath_project: "{{ source_asset_rootpath_project }}/{{ project_dir }}"
    dest_project_rootpath: "/home/{{ standard_user }}/{{ project_root_dir }}"
    dest_project_fullpath: "{{ dest_project_rootpath }}/{{ project_dir }}"

  roles:
    - name: ./roles/kwtoolset/copy_files_templating
      vars:
        copy_files_templating_dir_list:
          - src: "{{ source_asset_fullpath_common }}"
            dest: "{{ dest_project_rootpath }}"
            default_mode: "0775"
          - src: "{{ source_asset_fullpath_project }}"
            dest: "{{ dest_project_rootpath }}"
            default_mode: "0775"
    - name: ./roles/kwtoolset/container_pull
      vars:
        container_pull_list:
          - path: "{{ dest_project_fullpath }}"
            name: "{{ docker_compose_project_name }}"
            policy: "policy"
    - name: ./roles/kwtoolset/container_up
      vars:
        container_up_list:
          - path: "{{ dest_project_fullpath }}"
            name: "{{ docker_compose_project_name }}"
            ignore_errors: false

  post_tasks:
    - name: Add port {{ docker_metrics_addr_port }} to UFW from Docker network
      become: true
      become_user: root
      community.general.ufw:
        rule: allow
        direction: in
        proto: tcp
        from_ip: 172.16.0.0/12
        to_port: "{{ docker_metrics_addr_port }}"
      when:
        - docker_metrics_addr_host is defined
        - docker_metrics_addr_host | regex_search('^172')
