---
- name: Install and configure node_exporter with dependencies
  hosts: analytics_node
  become: false
  become_user: "{{ standard_user }}"
  vars:
    project_dir: node_exporter
    project_root_dir: "{{ analytics_node_project_structure_root }}"
    source_asset_rootpath_common: "{{ playbook_dir }}/assets/hosts-list/common/{{ project_root_dir }}"
    source_asset_fullpath_common: "{{ source_asset_rootpath_common }}/{{ project_dir }}"
    source_asset_rootpath_project: "{{ playbook_dir }}/assets/hosts-list/{{ inventory_hostname }}/{{ project_root_dir }}"
    source_asset_fullpath_project: "{{ source_asset_rootpath_project }}/{{ project_dir }}"
    dest_project_rootpath: "/home/{{ standard_user }}/{{ project_root_dir }}"
    dest_project_fullpath: "{{ dest_project_rootpath }}/{{ project_dir }}"

  roles:
    - name: ./roles/kwtoolset/copy_files_templating
      vars:
        copy_files_templating_dir_list:
          - src: "{{ source_asset_fullpath_common }}"
            dest: "{{ dest_project_rootpath }}"
            default_mode: "0775"
          - src: "{{ source_asset_fullpath_project }}"
            dest: "{{ dest_project_rootpath }}"
            default_mode: "0775"
    - name: prometheus.prometheus.node_exporter
      become: true
      become_user: root

  post_tasks:
    - name: Add port {{ node_exporter_web_listen_address_port | default('') }} to UFW from Docker network
      become: true
      become_user: root
      community.general.ufw:
        rule: allow
        direction: in
        proto: tcp
        from_ip: 172.16.0.0/12
        to_port: "{{ node_exporter_web_listen_address_port | default(omit) }}"
      when:
        - node_exporter_web_listen_address_host is defined
        - node_exporter_web_listen_address_host | regex_search('^172')
        - node_exporter_web_listen_address_port is defined
