---
# Tasks for deploying a single bot instance

- name: Stop and remove containers for this bot instance
  ansible.builtin.include_role:
    name: kwtoolset/container_stop_down
  vars:
    container_stop_down_list:
      - "{{ dest_project_fullpath }}"

- name: Copy templated files for this bot instance
  ansible.builtin.include_role:
    name: kwtoolset/copy_files_templating
  vars:
    copy_files_templating_dir_list:
      - src: "{{ source_asset_fullpath_common }}"
        dest: "{{ dest_project_fullpath }}"
        default_mode: "0775"

- name: Move contents of {{ dest_project_fullpath }}/{{ project_dir }} to {{ dest_project_fullpath }}
  ansible.builtin.shell:
    cmd: "cp -r {{ dest_project_fullpath }}/{{ project_dir }}/* {{ dest_project_fullpath }}/"
- name: Move contents of hidden files {{ dest_project_fullpath }}/{{ project_dir }} to {{ dest_project_fullpath }}
  ansible.builtin.shell:
    cmd: "mv --force {{ dest_project_fullpath }}/{{ project_dir }}/.env {{ dest_project_fullpath }}/"
  ignore_errors: true

- name: Copy templated files for this bot instance
  ansible.builtin.include_role:
    name: kwtoolset/copy_files_templating
  vars:
    copy_files_templating_dir_list:
      - src: "{{ source_asset_fullpath_project }}"
        dest: "{{ dest_project_fullpath_noindex }}"
        default_mode: "0775"

- name: Remove {{ dest_project_fullpath }}/{{ project_dir }}
  ansible.builtin.shell:
    cmd: "rm -rf {{ dest_project_fullpath }}/{{ project_dir }}"

- name: Pull container images for this bot instance
  ansible.builtin.include_role:
    name: kwtoolset/container_pull
  vars:
    container_pull_list:
      - path: "{{ dest_project_fullpath }}"
        name: "{{ project_name }}"
        policy: "policy"

- name: Start containers for this bot instance
  ansible.builtin.include_role:
    name: kwtoolset/container_up
  vars:
    container_up_list:
      - path: "{{ dest_project_fullpath }}"
        name: "{{ project_name }}"
        ignore_errors: false

- name: Add port {{ remna_server_caddy_tg_bot_jolymmiels_external_port }} to UFW (if defined)
  become: true
  become_user: root
  community.general.ufw:
    rule: allow
    port: "{{ remna_server_caddy_tg_bot_jolymmiels_external_port }}"
    proto: tcp
  when:
    - remna_server_caddy_tg_bot_jolymmiels_external_port is defined
    - remna_server_caddy_tg_bot_jolymmiels_external_port | length > 0

- name: Reminder to run install_ufw.yaml playbook (if port defined)
  ansible.builtin.debug:
    msg: |
      Reminder: Run the install_ufw.yaml playbook for host {{ inventory_hostname }} and environment.
      Example command: ansible-playbook -i {{ inventory_file | basename }} install_ufw.yaml --limit {{ inventory_hostname }}
  when:
    - remna_server_caddy_tg_bot_jolymmiels_external_port is defined
    - remna_server_caddy_tg_bot_jolymmiels_external_port | length > 0
