---
- name: Install and configure LogPorter
  hosts: analytics_node
  become: false
  become_user: "{{ standard_user }}"
  vars:
    project_dir: "{{ analytics_node_project_structure_end_dirs.logporter | ansible.builtin.basename }}"
    docker_compose_project_name: logporter
    project_root_dir: "{{ analytics_node_project_structure_root }}"
    source_asset_rootpath_common: "{{ playbook_dir }}/assets/hosts-list/common/{{ project_root_dir }}"
    source_asset_fullpath_common: "{{ source_asset_rootpath_common }}/{{ project_dir }}"
    source_asset_rootpath_project: "{{ playbook_dir }}/assets/hosts-list/{{ inventory_hostname }}/{{ project_root_dir }}"
    source_asset_fullpath_project: "{{ source_asset_rootpath_project }}/{{ project_dir }}"
    dest_project_rootpath: "/home/{{ standard_user }}/{{ project_root_dir }}"
    dest_project_fullpath: "{{ dest_project_rootpath }}/{{ project_dir }}"

  roles:
    - name: ./roles/kwtoolset/container_stop_down
      vars:
        container_stop_down_list:
          - "{{ dest_project_fullpath }}"
        docker_compose_project_name_list:
          - "{{ docker_compose_project_name }}"
    - name: ./roles/kwtoolset/copy_files_templating
      vars:
        copy_files_templating_dir_list:
          - src: "{{ source_asset_fullpath_common }}"
            dest: "{{ dest_project_rootpath }}"
            default_mode: "0775"
          - src: "{{ source_asset_fullpath_project }}"
            dest: "{{ dest_project_rootpath }}"
            default_mode: "0775"
    - name: ./roles/kwtoolset/container_pull
      vars:
        container_pull_list:
          - path: "{{ dest_project_fullpath }}"
            name: "{{ docker_compose_project_name }}"
            policy: "policy"
    - name: ./roles/kwtoolset/container_up
      vars:
        container_up_list:
          - path: "{{ dest_project_fullpath }}"
            name: "{{ docker_compose_project_name }}"
            ignore_errors: false

  pre_tasks:
    # Docker network
    - name: Ensure Docker network {{ analytics_node_network_name }} exists with specific settings
      community.docker.docker_network:
        name: "{{ analytics_node_network_name }}"
        driver: bridge
        state: present

  post_tasks:
    - name: Add port {{ logporter_exporter_external_port }} to UFW
      become: true
      become_user: root
      community.general.ufw:
        rule: allow
        port: "{{ logporter_exporter_external_port }}"
        proto: tcp
      when:
        - logporter_exporter_external_port is defined
        - logporter_exporter_external_port | length > 0
    - name: Reminder to run install_ufw.yaml playbook
      ansible.builtin.debug:
        msg: |
          Reminder: Run the install_ufw.yaml playbook for host {{ inventory_hostname }} and environment.
          Example command: ansible-playbook -i {{ inventory_file | basename }} install_ufw.yaml --limit {{ inventory_hostname }}
      when:
        - logporter_exporter_external_port is defined
        - logporter_exporter_external_port | length > 0