---
- name: Install web features - currently includes certcopy only
  hosts: all
  become: false
  become_user: "{{ standard_user }}"
  vars:
    project_dir: certcopy
    project_name: certcopy
    project_root_dir: "{{ webfeatures_project_structure_root }}"
    source_asset_rootpath_common: "{{ playbook_dir }}/assets/hosts-list/common/{{ project_root_dir }}"
    source_asset_fullpath_common: "{{ source_asset_rootpath_common }}/{{ project_dir }}"
    source_asset_rootpath_project: "{{ playbook_dir }}/assets/hosts-list/{{ inventory_hostname }}/{{ project_root_dir }}"
    source_asset_fullpath_project: "{{ source_asset_rootpath_project }}/{{ project_dir }}"
    dest_project_rootpath: "/home/{{ standard_user }}/{{ project_root_dir }}"
    dest_project_fullpath: "{{ dest_project_rootpath }}/{{ project_dir }}"

  roles:
    - name: ./roles/kwtoolset/copy_files
      vars:
        dir_list:
          - src: "{{ source_asset_fullpath_common }}"
            dest: "{{ dest_project_rootpath }}"
            default_mode: '0775'
          - src: "{{ source_asset_fullpath_project }}"
            dest: "{{ dest_project_rootpath }}"
            default_mode: '0775'

  post_tasks:
    - name: Verify if copy.sh exists
      ansible.builtin.stat:
        path: "{{ dest_project_fullpath }}/scripts/copy.sh"
      register: update_script_exists

    - name: Fail if copy.sh does not exist
      ansible.builtin.fail:
        msg: "The copy.sh script does not exist at {{ dest_project_fullpath }}/scripts/copy.sh"
      when: update_script_exists.stat.exists == false

    - name: Add cron job for certcopy
      ansible.builtin.cron:
        name: "Copy certs"
        minute: "{{ copy_certs_auto_renew_minute }}"
        hour: "{{ copy_certs_auto_renew_hour }}"
        job: "{{ dest_project_fullpath }}/scripts/copy.sh"
      when: update_script_exists.stat.exists == true

    - name: Create {{ cert_access_group }} group
      become: true
      become_user: root
      ansible.builtin.group:
        name: "{{ cert_access_group }}"
        state: present

