---
- name: Remove Autorestic on node
  hosts: all
  become: false
  become_user: "{{ standard_user }}"
  vars:
    project_dir: autorestic
    project_name: autorestic
    project_root_dir: "{{ backup_restic_node_project_structure_root }}"
    source_asset_rootpath_common: "{{ playbook_dir }}/assets/hosts-list/common/{{ project_root_dir }}"
    source_asset_fullpath_common: "{{ source_asset_rootpath_common }}/{{ project_dir }}"
    source_asset_rootpath_project: "{{ playbook_dir }}/assets/hosts-list/{{ inventory_hostname }}/{{ project_root_dir }}"
    source_asset_fullpath_project: "{{ source_asset_rootpath_project }}/{{ project_dir }}"
    dest_project_rootpath: "/home/{{ standard_user }}/{{ project_root_dir }}"
    dest_project_fullpath: "{{ dest_project_rootpath }}/{{ project_dir }}"

  roles:
    - name: ./roles/remove_project_dirs
      vars:
        remove_project_dirs: "['{{ dest_project_fullpath }}']"

  post_tasks:
    - name: Remove certbot cron job
      become: true
      become_user: root
      ansible.builtin.cron:
        name: "{{ restic_node_cron_job_name }}"
        state: absent
