---
roles:
  - src: geerlingguy.docker
  - src: linux-system-roles.journald
  - src: oefenweb.fail2ban
  - name: o1labs.systemd
    src: https://github.com/O1labs/ansible-role-systemd
    scm: git
    version: master

collections:
  - name: community.general
  - name: ansible.posix
  - name: prometheus.prometheus
  - name: devsec.hardening
