---
roles:
  - src: geerlingguy.docker
  - src: linux-system-roles.journald
  - src: oefenweb.fail2ban
  - src: 0x0I.systemd

collections:
  - name: community.general
  - name: ansible.posix
  - name: prometheus.prometheus
  - name: devsec.hardening
  - name: https://github.com/kenya-west/remnawave-ansible-collection
    type: git
    version: master
