---
# tasks file for configure_default_editor
- name: Check if micro editor is installed
  command: which micro
  register: micro_path
  ignore_errors: true

# - name: Set micro as default editor in ~/.bashrc
#   lineinfile:
#     path: ~/.bashrc
#     line: 'export EDITOR={{ micro_path.stdout }}'
#   when: micro_path.stdout != ''

- name: Set micro as alternative system-wide
  become: true
  become_user: root
  ansible.builtin.alternatives:
    name: editor
    link: /usr/bin/editor
    path: '{{ micro_path.stdout }}'
  when: micro_path.stdout != ''
