version: '3.8'

services:
  xray:
    image: teddysun/xray
    container_name: xray
    volumes:
      - ./config:/etc/xray
    ports:
      - ${XRAY_PORT}:23
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: "${DOMAIN}"
      caddy.import: "logging ${DOMAIN}"
      caddy.handle_path: "/${XRAY_WS_PATH}"
      caddy.handle_path.0_reverse_proxy: "{{upstreams ${XRAY_WS_PORT}}}"
      caddy.reverse_proxy: "lib.ru:80"

networks:
  caddy:
    external: true