---
- name: Install Certbot
  hosts: all
  become: true
  vars_files:
    - '{{ inventory_dir }}/vars/vars.yaml'

  vars:
    vpn_dir: vpn-xui-first
    project_dir: certbot
    source_asset_fullpath: "{{ inventory_dir }}/assets/xui-first"
    dest_project_fullpath: "/home/{{ standard_user }}/{{ vpn_dir }}/{{ project_dir }}"
    certbot_create_extra_args: ""
    certbot_create_if_missing: true
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ standard_user }}"
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "30"
    certbot_auto_renew_options: "--quiet"
    certbot_admin_email: "{{ env_vars['EMAIL'] }}"
    certbot_certs:
      - domains:
          - "{{ env_vars['DOMAIN'] }}"

  pre_tasks:
    - name: Get env file content
      set_fact:
        env_lines: "{{ lookup('file', '{{ source_asset_fullpath }}/.env-{{ inventory_hostname }}') }}"

    - name: Set environment variables from .env file
      set_fact:
        env_vars: "{{ env_lines.split('\n') | map('regex_replace', '^#.*', '') | select | map('regex_replace', '([^=]*)=(.*)', '\\1: \\2') | join('\n') | from_yaml }}"

    - name: Debug env_vars
      debug:
        var: env_vars

  roles:
    - role: geerlingguy.certbot
      tags: certbot

  tasks:
    - name: List all directories in /etc/letsencrypt/live
      find:
        paths: /etc/letsencrypt/live
        file_type: directory
      register: live_dirs

    - name: Show directories in /etc/letsencrypt/live
      debug:
        var: live_dirs.files | map(attribute='path')

    - name: List all files and directories in {{ env_vars['DOMAIN'] }} directory
      find:
        paths: "/etc/letsencrypt/live/{{ env_vars['DOMAIN'] }}"
      register: domain_files

    - name: Show files and directories in /etc/letsencrypt/live/{{ env_vars['DOMAIN'] }}
      debug:
        var: domain_files.files | map(attribute='path')