---
- name: Install X-UI API Server
  hosts: all
  become: true
  become_user: "{{ standard_user }}"
  vars_files:
    - '{{ inventory_dir }}/vars/vars.yaml'
  vars:
    vpn_dir: vpn-xui-first
    project_dir: xui-api-server
    source_asset_fullpath: "{{ inventory_dir }}/assets/{{ vpn_dir }}/{{ project_dir }}"
    dest_project_fullpath: "/home/{{ standard_user }}/{{ vpn_dir }}/{{ project_dir }}"

  tasks:
  # Validate fiels and folders exist
  - name: Ensure ~/project directory exists
    file:
      path: "{{ dest_project_fullpath }}/"
      state: directory
      mode: '0775'
  # Stop and down if it was up
  - name: Check status of Docker Compose services
    command: docker compose ps
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: docker_compose_status
    ignore_errors: yes
  - name: Stop X-UI service if it is running
    command: docker compose down xui-api-server
    args:
      chdir: "{{ dest_project_fullpath }}/"
    when: "'xui-api-server' in docker_compose_status.stdout"
    ignore_errors: yes
  - name: Pull new X-UI release service if it was running
    command: docker compose pull xui-api-server
    args:
      chdir: "{{ dest_project_fullpath }}/"
    when: "'xui-api-server' in docker_compose_status.stdout"
    ignore_errors: yes
  # Copy files
  - name: Copy all files from "{{ source_asset_fullpath }}" to remote "{{ dest_project_fullpath }}"
    copy:
      src: "{{ source_asset_fullpath }}/{{ item.sourcename }}"
      dest: "{{ dest_project_fullpath }}/{{ item.destname }}"
    loop:
      - sourcename: "docker-compose.yml"
        destname: "docker-compose.yml"
    register: copy_files_root
  # Network existing check
  - name: Ensure Docker network 'xui_network' exists with specific settings
    docker_network:
      name: xui_network
      driver: bridge
      state: present
  # Up the service
  - name: Run docker compose up for X-UI API Server
    command: docker compose up xui-api-server -d
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: docker_compose_up
  - name: Wait for 3 seconds after starting docker compose
    pause:
      seconds: 3
    when: docker_compose_up.changed
  - name: Check if X-UI API Server service is running correctly
    command: docker compose ps xui-api-server
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: docker_ps
    failed_when: "'Up' not in docker_ps.stdout"
    when: docker_compose_up.changed
