---
# tasks file for roles/install_docker

- name: Gather service facts
  ansible.builtin.service_facts:

- name: Detect country from IP when no override is set
  block:
    - name: Get IP geolocation data
      ansible.builtin.include_role:
        name: get_ip_data
      vars:
        get_ip_data_required_fields: ['country_code']
        get_ip_data_policy: check_all

    - name: Set country from IP data
      ansible.builtin.set_fact:
        docker_mirrors_country: "{{ ip_data.country_code }}"
      when: ip_data.country_code | length > 0

    - name: Debug country information
      ansible.builtin.debug:
        msg: "The country for host {{ inventory_hostname }} with ip {{ ip_data.ip }} is {{ docker_mirrors_country }}"
      when: ip_data.country_code | length > 0
  when: enforce_country_code is not defined or enforce_country_code is not string or enforce_country_code | length == 0

- name: Use forced country override
  ansible.builtin.set_fact:
    docker_mirrors_country: "{{ enforce_country_code }}"
  when:
    - enforce_country_code is defined
    - enforce_country_code is string
    - enforce_country_code | length > 0

- name: Normalize country code to uppercase
  ansible.builtin.set_fact:
    docker_mirrors_country_normalized: "{{ docker_mirrors_country | upper }}"
    docker_mirrors_country_code_allowlist_normalized: "{{ docker_mirrors_country_code_allowlist | map('upper') | list }}"
  when:
    - docker_mirrors_country is defined
    - docker_mirrors_country_code_allowlist is defined

- name: Set docker_repo_url fact based on country code
  ansible.builtin.set_fact:
    docker_repo_url: >-
      {{ (
            docker_mirrors
            | selectattr('preferred_country_code', 'equalto', docker_mirrors_country_normalized)
            | map(attribute='url')
            | first
          ) | default('https://download.docker.com/linux')
      }}
  when:
    - docker_mirrors_country_normalized is defined
    - docker_mirrors_country_normalized in docker_mirrors_country_code_allowlist_normalized

- name: Display the selected Docker repository URL
  ansible.builtin.debug:
    msg: "Selected Docker repository URL: {{ docker_repo_url }} because the country code is {{ docker_mirrors_country_normalized }}"
  when:
    - docker_mirrors_country_normalized is defined
    - docker_mirrors_country_normalized in docker_mirrors_country_code_allowlist_normalized
    - docker_repo_url is defined

- name: Run geerlingguy.docker role to install Docker
  ansible.builtin.include_role:
    name: geerlingguy.docker
