---

- import_playbook: ../reverse_proxy/certcopy.yaml

# Step 3: Install backup tools
- import_playbook: ../backup/node/rclone.yaml
- import_playbook: ../backup/node/restic.yaml

# Step 4: Final configuration
- import_playbook: ../networking/ufw.yaml
