- name: Check if path exists
  ansible.builtin.stat:
    path: "{{ item }}"
  register: container_stop_down_path_stat
- name: Check if docker-compose.yml exists in the path
  ansible.builtin.stat:
    path: "{{ item }}/docker-compose.yml"
  register: container_stop_down_compose_stat
  when: container_stop_down_path_stat.stat.exists
- name: Add valid path to the filtered list
  ansible.builtin.set_fact:
    container_stop_down_list_filtered: "{{ container_stop_down_list_filtered + [item] }}"
  when:
    - container_stop_down_path_stat.stat.exists
    - container_stop_down_compose_stat.stat.exists
