---
- name: Show backup keys for Autorestic
  hosts: backup_restic_node
  become: false
  become_user: "{{ standard_user }}"

  vars:
    role_scenarios:
      - show_keys

  roles:
    - role: install_backup_node_restic