---
- import_playbook: ../reverse_proxy/caddy.yaml
- import_playbook: ../reverse_proxy/frp.yaml
- import_playbook: ../vpn/wg.yaml
- import_playbook: ../anti_censorship/node/remna.yaml
- import_playbook: ../anti_censorship/node/zapret.yaml
- import_playbook: ../reverse_proxy/certcopy.yaml
- import_playbook: ../networking/ufw.yaml
