version: '3.8'
services:
  frps:
    image: kenyawest/frps-dockerized:latest
    container_name: frps
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./config-frps/frps.toml.template
        target: /etc/frp/frps.toml.template
      - certs:/etc/frp/certs
    network_mode: host

  frpc:
    image: kenyawest/frpc-dockerized:latest
    container_name: frpc
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./config-frpc/frpc.toml.template
        target: /etc/frp/frpc.toml.template
      - certs:/etc/frp/certs
    network_mode: host

networks:
  caddy:
    external: true

volumes:
  certs:
    external: true
    name: caddy_caddy-certs