# The commented vars should be set in host_vars or in playbook

proxy_client_frpc_server_address: sub.example.tld
proxy_client_frpc_server_port: 7000
proxy_client_frpc_client_dashboard_port: 7400
proxy_client_frpc_client_dashboard_user: username
# proxy_client_frpc_client_dashboard_password: password
proxy_client_frpc_client_auth_method: token
# proxy_client_frpc_client_auth_token: sometoken
