frps_web_telemetry_path: "/{{ path_to_internal_services_predefined_full }}/frps_exporter/metrics"

frp_web_external_port: 48510

caddy_external_ports_allowlist__frp:
  - '{{ frp_web_external_port }}:{{ frp_web_external_port }}'