remna_protocol_types:
  vless_reality_tcp:
    parts:
      - vless
      - reality
      - tcp
    root: vless
    short: reality-tcp
    full: vless-reality-tcp
  vless_reality_xhttp:
    parts:
      - vless
      - reality
      - xhttp
    root: vless
    short: reality-xhttp
    full: vless-reality-xhttp

remna_node_primary_protocol_type: "{{ remna_protocol_types.vless_reality_tcp }}"
