restic_node_vars:
  locations:
    home_user:
      from: "/home/{{ standard_user }}"
      to:
        - restic-rest-server
      tobereplacedwith: "cron" # This will be replaced to alias defined in .autorestic.yaml.j2
      options:
        tobereplacedwith: "complete_options" # This will be replaced to alias defined in .autorestic.yaml.j2
    shared_ssl:
      from: "{{ cert_location_root_path }}"
      to:
        - restic-rest-server
      options:
        tobereplacedwith: "complete_options" # This will be replaced to alias defined in .autorestic.yaml.j2
  remotes:
    restic-rest-server:
      type: rest
      path: "<restic_rest_server_url>/{{ inventory_hostname }}/"
      # On first launch, this prop below should not exist.
      # Then, after the first backup, you should set it to the key value from the restic server
      key: <restic_rest_remote_key>
      rest:
        user: <restic_rest_server_user>
        password: <restic_rest_server_password>
    <remote_name>:
      type: <remote_type>
      host: "<remote_host>/{{ inventory_hostname }}/"
      # On first launch, this prop below should not exist.
      # Then, after the first backup, you should set it to the key value from the restic server
      key: <restic_rest_remote_key>
      port: <remote_port>
      user: <remote_user>