restic_node_vars:
  locations: "{{ backup_restic_node_locations }}"
  remotes: >-
    {{ lookup('vars','backup_restic_node_remotes')
      | combine(
          { 
            'your_location_name': { 
              'key': '<key_from_encrypted_restic_file_made_after_first_backup>'
            },
            'your_location_name2': { 
              'key': '<key_from_encrypted_restic_file_made_after_first_backup>'
            }
          },
          recursive=True
        )
    }}