---
backup_restic_node_project_structure_end_dirs__base:
  pgdump: "{{ backup_restic_node_project_structure_root }}/pgdump"
  pgdumpany_subdirectory_name: "{{ backup_restic_node_project_structure_root }}/any_subdirectory_name"

backup_restic_node_project_structure_end_dirs: >-
  {{
    lookup('community.general.merge_variables',
           '^backup_restic_node_project_structure_end_dirs__.*',
           wantlist=True
          )
    | combine({}, recursive=False)
  }}
backup_restic_node_project_structure_end_dirs_list: "{{ backup_restic_node_project_structure_end_dirs.values() | list }}"
