- name: Get dirname of the project
  set_fact:
    container_pull_service_dirname: "{{ item.path | basename }}"

- name: Get list of services defined in docker-compose.yml
  command: yq eval '.services | keys | .[]' docker-compose.yml
  register: container_pull_services_list
  when: container_pull_yq_installed is not failed and container_pull_yq_installed.stdout != ""
  failed_when:
    - container_pull_services_list.rc != 0
    - container_pull_services_list.rc != 1

- name: Docker Compose project - container pull
  community.docker.docker_compose_v2_pull:
    project_src: "{{ item.path }}"
    project_name: "{{ item.name | default(container_pull_service_dirname) }}"
    files:
      - docker-compose.yml
  register: container_pull_running
  ignore_errors: "{{ item.ignore_errors | default(false) }}"

