---
# tasks file for roles/update
- name: Ensure apt list dir exists
  ansible.builtin.file:
    path: /var/lib/apt/lists/
    state: directory
    mode: "0755"
- name: Update & refresh packages
  ansible.builtin.apt:
    update_cache: "yes"
    cache_valid_time: "3600"
- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist
