---
# defaults file for roles/install_vpn_caddy_remna
project_dir: "{{ vpn_project_structure_end_dirs.remna | ansible.builtin.basename }}"
project_root_dir: "{{ vpn_project_structure_root }}"
source_asset_rootpath_project: "{{ location_custom_files_path }}/{{ project_root_dir }}"
source_asset_fullpath_project: "{{ source_asset_rootpath_project }}/{{ project_dir }}/"

source_paths_add_role_dirs:
  - templates
source_paths_add_repo_dirs:
  - "{{ source_asset_fullpath_project }}"
source_paths_add_user_dirs: []

dest_path_root: "/home/{{ standard_user }}/{{ vpn_project_structure_root }}"
dest_path_full: "{{ dest_path_root }}/{{ project_dir }}"

compose_project_name: "{{ project_dir }}"

remna_node_app_port: 2220
remna_node_control_port: 48540
remna_node_external_ports: []
remna_node_use_dns01_cloudflare: false