---
- name: Install OhMyPosh
  hosts: all
  vars_files:
    - "{{ inventory_dir }}/vars/vars.yaml"
  become: true
  become_user: "{{ standard_user }}"
  vars:
    dest_project_fullpath: "/home/{{ standard_user }}"

    script_dir: "{{ dest_project_fullpath }}/oh-my-posh"
    themes_dir: "{{ dest_project_fullpath }}/.poshthemes"
    theme: illusi0n

  tasks:
  - file:
      state: directory
      path: "{{ script_dir }}"
      mode: 0775
  - file:
      state: directory
      path: "{{ themes_dir }}"
      mode: 0775
  
  - name: Change script and themes permissions
    command: "{{ item }}"
    with_items: 
    - "chmod -R 775 {{ script_dir }}"
    - "chmod -R 775 {{ themes_dir }}"

  - name: Download oh-my-posh
    get_url:
      url: https://ohmyposh.dev/install.sh
      validate_certs: false
      dest: "{{ script_dir }}/install.sh"

  - name: Download oh-my-posh themes
    get_url:
      url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip
      dest: "{{ themes_dir }}"
      force: true

  - name: Rename themes file
    shell: "mv {{ themes_dir }}/themes.zip {{ themes_dir }}/themes.zip.gz"  
  
  - name: Change themes permissions
    command: "{{ item }}"
    with_items: 
    - "chmod -R 775 {{ themes_dir }}"

  - name: Unzip themes by two ways
    block:
      - name: Unzip oh-my-posh themes by built-in unarchive module
        unarchive:
          src: "{{ themes_dir }}/themes.zip.gz"
          dest: "{{ themes_dir }}"
    rescue:
      - name: Unzip oh-my-posh themes by shell module with unzip tool
        shell: "unzip -o {{ themes_dir }}/themes.zip.gz -d {{ themes_dir }}"

  - name: Change themes permissions
    command: "{{ item }}"
    with_items: 
    - "chmod -R 775 {{ themes_dir }}"

  - name: Remove themes archive
    file:
      state: absent
      path: "{{ themes_dir }}/themes.zip.gz"

  - name: Change script permissions
    command: "{{ item }}"
    with_items: 
    - "chmod -R 775 {{ script_dir }}"

  - name: Install oh-my-posh
    become: true
    become_user: root
    command: "{{ script_dir }}/install.sh -d /usr/local/bin"
    args:
      creates: "/root/usr/bin/oh-my-posh"

  - name: Install Nerd fonts
    command: "oh-my-posh font install CascadiaCode"

  - name: Ensure that profile exists
    file:
      path: "{{ dest_project_fullpath }}/.profile"
      state: touch

  - name: Remove oh-my-posh obsolete line from profile
    lineinfile:
      path: "{{ dest_project_fullpath }}/.profile"
      regexp: eval\s\"\$\(oh-my-posh.+
      state: absent
      backup: yes

  - name: Add oh-my-posh to profile
    lineinfile:
      path: "{{ dest_project_fullpath }}/.profile"
      line: "eval \"$(oh-my-posh init bash --config {{ themes_dir }}/{{ theme }}.omp.json)\""

  - name: Remove scripts directory
    file:
      state: absent
      path: "{{ script_dir }}"
    ignore_errors: yes
