---
- name: Install Docker
  hosts: local
  become: true
  vars_files:
    - '{{ inventory_dir }}/vars/vars.yaml'

  vars:
    docker_users:
      - "{{ standard_user }}"
    docker_package_state: present

  pre_tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      failed_when: false
      changed_when: false

    - name: Set docker_package_state to absent if Docker is installed
      set_fact:
        docker_package_state: absent
      when: docker_installed.rc == 0

  roles:
    - role: geerlingguy.docker
      when: docker_package_state == 'present'