---
- name: Configure Bash Profile
  hosts: all
  become: true
  vars_files:
    - "{{ inventory_dir }}/vars/vars.yaml"
  tasks:
    - name: Read aliases from local .bashrc file
      set_fact:
        aliases_content: "{{ lookup('file', inventory_dir + '/assets/bash/.bashrc', errors='ignore').split('\n') }}"
      failed_when: aliases_content == ['']
      ignore_errors: yes

    - name: Ensure .bashrc exists on target machine
      file:
        path: "/home/{{ standard_user }}/.bashrc"
        state: touch
        mode: '0644'
      when:
        - aliases_content is defined
        - aliases_content != ['']
      ignore_errors: yes

    - name: Add aliases to .bashrc if not present
      lineinfile:
        path: "/home/{{ standard_user }}/.bashrc"
        line: "{{ item }}"
        state: present
        create: yes
        insertafter: EOF
      with_items: "{{ aliases_content }}"
      when:
        - item != ''
        - aliases_content is defined
        - aliases_content != ['']
      ignore_errors: yes
