---
- name: Install packages
  hosts: local
  become: true
  vars_files:
    - '{{ inventory_dir }}/vars/vars.yaml'
  tasks:
  - name: Install Apt packages
    ignore_errors: yes
    apt:
      state: latest
      update_cache: yes
      pkg:
      - tree
      - neofetch
      - bat
      - exa
      - fd-find
      - fzf
      - httpie
      - xh
      - cron
      - hstr
      - duf
      - jq
      - zoxide
      - whois
  - name: Install Snap packages
    community.general.snap:
      name:
        # - tldr # not found, too
        - procs
  