---
- name: Install packages
  hosts: all
  become: true
  vars_files:
    - '{{ inventory_dir }}/vars/vars.yaml'
  vars:
    packages:
      # Base packages
      - bash
      - curl
      - wget
      - unzip
      - ncdu
      - tree
      - gpg
      - gettext-base
      # Extra packages
      - moreutils
      - neofetch
      - bat # Ensure this is available or add a task to include its repository
      - fd-find # Use 'fd' for Ubuntu/Debian, might need a PPA
      - fzf
      - httpie
      - xh
      - cron
      - hstr
      - duf
      - jq
      - zoxide
      - whois
      - ripgrep
      - micro
      - btop
      # Service packages
      - python3-docker # Needed for Ansible Docker modules

  tasks:
  - name: Install Apt packages
    ignore_errors: yes
    ansible.builtin.apt:
      update_cache: yes
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"

  - name: Install Snap packages
    ignore_errors: yes
    community.general.snap:
      name:
        - procs
