---
- name: Configure Bash Profile
  hosts: all
  become: true
  become_user: "{{ standard_user }}"
  vars_files:
    - "{{ inventory_dir }}/vars/vars.yaml"
  vars:
    project_dir: bash
    source_asset_fullpath: "{{ inventory_dir }}/assets/general-machine-prepare/{{ project_dir }}"
    dest_project_fullpath: "/home/{{ standard_user }}/"
  tasks:
    - name: Read aliases from local .bashrc file
      set_fact:
        aliases_content: "{{ lookup('file', source_asset_fullpath + '/.bashrc', errors='ignore').splitlines() }}"
      failed_when: aliases_content == ['']
      ignore_errors: yes

    - name: Ensure .bashrc exists on target machine
      file:
        path: "{{ dest_project_fullpath }}/.bashrc"
        state: touch
        mode: '0644'
      when:
        - aliases_content is defined
        - aliases_content != ['']
      ignore_errors: yes

    - name: Add aliases to .bashrc if not present
      lineinfile:
        path: "{{ dest_project_fullpath }}/.bashrc"
        line: "{{ item }}"
        state: present
        create: yes
        insertafter: EOF
      with_items: "{{ aliases_content }}"
      when:
        - item != ''
        - aliases_content is defined
        - aliases_content != ['']
      ignore_errors: yes
