---
- name: Ensure eget is installed and updated
  hosts: all
  become: true
  vars_files:
    - "{{ inventory_dir }}/vars/vars.yaml"

  tasks:
    - name: Check if eget is already installed
      command: which eget
      register: eget_installed
      ignore_errors: true

    - name: Download tstack/lnav
      command: 'eget tstack/lnav --asset lnav --to /usr/local/bin'
      when: eget_installed.rc == 0
      ignore_errors: true

    - name: Download koenbollen/jl
      command: 'eget koenbollen/jl --to /usr/local/bin'
      when: eget_installed.rc == 0
      ignore_errors: true

    - name: Download mikefarah/yq
      command: 'eget mikefarah/yq --asset yq_linux_amd64 --to /usr/local/bin'
      when: eget_installed.rc == 0
      ignore_errors: true
