---
- name: Ensure eget is installed and updated
  hosts: all
  become: true
  vars_files:
    - "{{ inventory_dir }}/vars/vars.yaml"

  tasks:
    - name: Check if eget is already installed
      command: which eget
      register: eget_installed
      ignore_errors: true

    - name: Download eget installation script
      get_url:
        url: https://zyedidia.github.io/eget.sh
        dest: /tmp/eget.sh
        mode: '0755'
      when: eget_installed.rc != 0

    - name: Run eget.sh to install eget
      shell: "bash /tmp/eget.sh"
      when: eget_installed.rc != 0

    - name: Run eget to update itself
      command: eget zyedidia/eget
      when: eget_installed.rc == 0

    - name: Move eget binary to /usr/local/bin
      command: mv /home/{{ standard_user }}/eget /usr/local/bin/
      args:
        creates: /usr/local/bin/eget

    - name: Remove eget.sh
      file:
        path: /tmp/eget.sh
        state: absent
    
    - name: Remove eget binary file in user directory
      file:
        path: /home/{{ standard_user }}/eget
        state: absent
