---
- name: Install OhMyPosh
  hosts: local
  become: true
  vars_files:
    - '{{ inventory_dir }}/vars/vars.yaml'
  vars:
    script_dir: oh-my-posh
    themes_dir: .poshthemes
    theme: illusi0n

  tasks:
  - file:
      state: directory
      path: "/home/{{ standard_user }}/{{ script_dir }}"
  - file:
      state: directory
      path: "/home/{{ standard_user }}/{{ themes_dir }}"

  - name: Download oh-my-posh
    get_url:
      url: https://ohmyposh.dev/install.sh
      validate_certs: false
      dest: "/home/{{ standard_user }}/{{ script_dir }}/install.sh"

  - name: Download and unzip oh-my-posh themes
    ansible.builtin.unarchive:
      src: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip
      validate_certs: false
      dest: "/home/{{ standard_user }}/{{ themes_dir }}"
      remote_src: yes

  - name: Change script and themes permissions
    command: "{{ item }}"
    with_items: 
    - "chmod -R 775 /home/{{ standard_user }}/{{ script_dir }}"
    - "chmod -R 775 /home/{{ standard_user }}/{{ themes_dir }}"

  - name: Install oh-my-posh
    command: "/home/{{ standard_user }}/{{ script_dir }}/install.sh"

  - name: Install Nerd fonts
    command: "oh-my-posh font install CascadiaCode"

  - name: Ensure that profile exists
    ansible.builtin.copy:
      dest: "/home/{{ standard_user }}/.profile"
      content: ""
      force: no

  - name: Remove oh-my-posh obsolete line from profile
    ansible.builtin.lineinfile:
      path: "/home/{{ standard_user }}/.profile"
      regexp: eval\s\"\$\(oh-my-posh.+
      state: absent
      backup: yes

  - name: Add oh-my-posh to profile
    ansible.builtin.lineinfile:
      path: "/home/{{ standard_user }}/.profile"
      line: "eval \"$(oh-my-posh init bash --config /home/{{ standard_user }}/{{ themes_dir }}/{{ theme }}.omp.json)\""

  - name: Remove scripts directory
    file:
      state: absent
      path: "/home/{{ standard_user }}/{{ script_dir }}"
    ignore_errors: yes
