---
# defaults file for roles/install_vpn_caddy_tblocker
project_dir: "{{ vpn_project_structure_end_dirs.tblocker | ansible.builtin.basename }}"
project_root_dir: "{{ vpn_project_structure_root }}"
source_asset_rootpath_project: "{{ location_custom_files_path }}/{{ project_root_dir }}"
source_asset_fullpath_project: "{{ source_asset_rootpath_project }}/{{ project_dir }}/"

source_paths_add_role_dirs:
  - templates
source_paths_add_repo_dirs:
  - "{{ source_asset_fullpath_project }}"
source_paths_add_user_dirs: []

dest_path_root: "/home/{{ standard_user }}/{{ vpn_project_structure_root }}"
dest_path_full: "{{ dest_path_root }}/{{ project_dir }}"
dest_path_full_systemd: "/etc/systemd/system"

compose_project_name: "{{ project_dir }}"