---

vpn_project_structure_root: vpn-caddy
vpn_project_structure_end_dirs__base:
  frp: "{{ vpn_project_structure_root }}/frp"
  remna: "{{ vpn_project_structure_root }}/remna"
  wg: "{{ vpn_project_structure_root }}/wg"
  caddy: "{{ vpn_project_structure_root }}/caddy"
vpn_project_structure_end_dirs: "{{ vpn_project_structure_end_dirs__base }}"
vpn_project_structure_end_dirs_list: "{{ vpn_project_structure_end_dirs.values() | list }}"

main_webserver:
  path: "{{ vpn_project_structure_end_dirs.caddy }}"
  name: caddy

webfeatures_project_structure_root: web-features-caddy
webfeatures_project_structure_end_dirs:
  main: "{{ webfeatures_project_structure_root }}/certcopy"
  certcopy: "{{ webfeatures_project_structure_root }}/certcopy"
webfeatures_project_structure_end_dirs_list: "{{ webfeatures_project_structure_end_dirs.values() | list }}"
