caddy_external_ports_allowlist: >-
  {{
    lookup('community.general.merge_variables',
           '^caddy_external_ports_allowlist__.*',
           wantlist=True,
           list_merge='append_rp'
          )
    | flatten
    | unique
  }}
