---
- name: Install and configure Grafana with dependencies
  hosts: analytics_server
  become: false
  become_user: "{{ standard_user }}"
  roles:
    - name: kwtoolset/resolve_host_relations
      vars:
        resolve_host_relations_group: analytics_server
        resolve_host_relations_component: grafana
    - install_analytics_server_grafana
