---
# tasks file for roles/clear_cache
- name: Clear Apt cache
  ansible.builtin.apt:
    clean: true

- name: Remove Snap cache files
  ansible.builtin.shell: "rm -rf /var/lib/snapd/cache/*"
  ignore_errors: true
  register: snap_cache_cleanup
  changed_when: snap_cache_cleanup.rc == 0

- name: Display result of Snap cache cleanup
  ansible.builtin.debug:
    msg: "Snap cache cleaned successfully."
  ignore_errors: true
  when: snap_cache_cleanup.rc == 0

- name: Truncate all log files in /var/log
  ansible.builtin.find:
    paths: /var/log
    recurse: true
    file_type: file
  ignore_errors: true
  register: log_files
- name: Clear contents of log files
  ansible.builtin.command: "truncate -s 0 {{ item.path }}"
  loop: "{{ log_files.files }}"
  ignore_errors: true
  when: log_files.matched > 0
