# This variable defines the last part of the path to the certificate and key files.
# It remaps domains_keys variable.
# Depends on whether it is a Caddy or a Certbot path style.
# This is for Caddy server.

cert_location_path_section: >-
  {{
    dict(
      domains_keys.keys() | zip(
        domains_keys.values() | map('regex_replace', '^(.*)$', '\g<1>')
      ) +
      (
        domains_keys.keys() | map('regex_replace', '^(.*)$', '\1_crt')
        | zip(
            domains_keys.values() | map('regex_replace', '^(.*)$', '\g<1>/\g<1>.crt')
          )
      ) +
      (
        domains_keys.keys() | map('regex_replace', '^(.*)$', '\1_key')
        | zip(
            domains_keys.values() | map('regex_replace', '^(.*)$', '\g<1>/\g<1>.key')
          )
      )
    )
  }}
