domains_keys:
  main: sub.example.tld
  prometheus: sub-prometheus.example.tld
  grafana: sub-grafana.example.tld
  victoriametrics: sub-victoriametrics.example.tld
  victorialogs: sub-victorialogs.example.tld
  pushgateway: sub-pushgateway.example.tld
domains: "{{ domains_keys.values() | list | unique }}"