services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/config.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./config:/etc/prometheus
      - prom_data:/prometheus

volumes:
  prom_data: