---
# tasks file for roles/remove_vpn

- name: Check if the directory exists
  ansible.builtin.stat:
    path: "{{ item }}"
  register: dir_stat
  loop: "{{ remove_project_dirs }}"
  loop_control:
    loop_var: item

- name: Output directory existence status
  ansible.builtin.debug:
    msg: "Directory {{ item }} existence: {{ dir_stat.results[item_index].stat.exists }}"
  loop: "{{ remove_project_dirs }}"
  loop_control:
    loop_var: item
    index_var: item_index

- name: Destroy docker-compose project
  ansible.builtin.include_tasks: destroy.yml
  loop: "{{ remove_project_dirs }}"
  loop_control:
    loop_var: item

- name: Remove the directory if it exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  when: dir_stat.results[item_index].stat.exists
  loop: "{{ remove_project_dirs }}"
  loop_control:
    loop_var: item
    index_var: item_index
  ignore_errors: true
