---
# tasks file for roles/remove_vpn

  - name: Check if the directory exists
    stat:
      path: "{{ item }}"
    register: dir_stat
    loop: "{{ remove_project_dirs }}"
    loop_control:
      loop_var: item

  - name: Output directory existence status
    debug:
      msg: "Directory {{ item }} existence: {{ dir_stat.results[item_index].stat.exists }}"
    loop: "{{ remove_project_dirs }}"
    loop_control:
      loop_var: item
      index_var: item_index
  
  - name: Destroy docker-compose project
    include_tasks: destroy.yml
    loop: "{{ remove_project_dirs }}"
    loop_control:
      loop_var: item

  - name: Remove the directory if it exists
    file:
      path: "{{ item }}"
      state: absent
    when: dir_stat.results[item_index].stat.exists
    loop: "{{ remove_project_dirs }}"
    loop_control:
      loop_var: item
      index_var: item_index
    ignore_errors: yes