- name: Force unlock restic repository
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: "./scripts/unlock-force.sh"
    chdir: "{{ dest_path_full }}"
  register: unlock_result

- name: Assert that the unlock was successful
  ansible.builtin.assert:
    that:
      - unlock_result.rc == 0
      - '"Unlock successful" in unlock_result.stdout'
    fail_msg: "Failed to unlock the restic repository. Please check the output for details."
  tags:
    - show_keys

- name: Show keys by running key.sh script
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: "./scripts/key.sh"
    chdir: "{{ dest_path_full }}"
  register: keys
  tags:
    - show_keys

- name: Debug the keys
  debug:
    msg: "{{ keys.stdout_lines
        + ['']
        + ['❗ You must save these keys in a secure location.']
        + ['📁 Suggested file: '
           ~ inventory_dir
           ~ '/host_vars/'
           ~ inventory_hostname
           ~ '/backup_restic_node/'
           ~ 'backup_restic_node.yaml'
          ] }}"
  tags:
    - show_keys