---
# tasks file for roles/install_ufw
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
- name: Allow collected ports in UFW (for TCP)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ ufw_ports }}"
  when:
    - input_mode is not defined or input_mode == 'list'
    - "'tcp' in ufw_protos"
- name: Allow collected ports in UFW (for UDP)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop: "{{ ufw_ports }}"
  when:
    - input_mode is not defined or input_mode == 'list'
    - "'udp' in ufw_protos"
- name: Set rules for UFW on complex mode
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw_rules }}"
  when:
    - input_mode is defined
    - input_mode == 'complex'