version: '3.8'
services:
  frps:
    image: snowdreamtech/frps
    container_name: frps
    restart: unless-stopped
    ports:
      - ${FRPS_SERVER_PORT}:${FRPS_SERVER_PORT}
      - "${FRPS_RANGE_PORTS_1_START}-${FRPS_RANGE_PORTS_1_END}:${FRPS_RANGE_PORTS_1_START}-${FRPS_RANGE_PORTS_1_END}/tcp"
    env_file:
      - .env
    volumes:
      - ./config-frps:/etc/frp
      - certs:/etc/frp/certs
    networks:
      - caddy
    labels:
      caddy: "${DOMAIN}"
      caddy.import: "logging ${DOMAIN}"
      caddy.0_reverse_proxy: "{{upstreams ${FRPS_DASHBOARD_PORT}}}"

  frpc:
    image: snowdreamtech/frpc
    container_name: frpc
    restart: unless-stopped
    volumes:
      - ./config-frpc:/etc/frp
      - certs:/etc/frp/certs
    network_mode: host

networks:
  caddy:
    external: true

volumes:
  certs:
    external: true
    name: caddy_caddy-certs