vpn_server_remnawave_tgbot_bedolaga_settings_global:
  service_name_prefix: remnawave-telegram-tgbot-bedolaga

vpn_server_remnawave_tgbot_bedolaga_settings:
  - name: main
    bot_token: <123456789:ABC-DEF1234ghIkl-zyx57W2v1u123ew11> # Telegram bot token that you create in https://t.me/BotFather
    admin_ids: []

    domain: "{{ domains_keys.remnawave_tgbot_bedolaga }}" # no https:// prefix
    # external_port: -1
    run_mode: webhook

    webhook_url: "{{ domains_keys.remnawave_tgbot_bedolaga }}" # no https:// prefix
    webhook_secret_token: ""

    web_api_enabled: true
    web_api_port: 8080
    web_api_allowed_origins: >-
      {{
        [
          domains_keys.remnawave_tgbot_bedolaga
        ]
        + (
          [domains_keys.remnawave_tgbot_bedolaga_cabinet]
          if domains_keys.remnawave_tgbot_bedolaga_cabinet is defined
          else []
        )
      }}
    web_api_default_token: ""

    remnawave_api_url: "your-panel.com" # no https:// prefix
    remnawave_api_key: ""
    # remnawave_auth_type: caddy # uncomment if remnawave_caddy_token is set
    remnawave_caddy_token: ""

    sales_mode: tariffs # or classic
    multi_tariff_enabled: false
    max_active_subscriptions: 1

    trial_duration_days: 14
    trial_traffic_limit_gb: 15
    trial_device_limit: 2
    trial_payment_enabled: false
    trial_activation_price: 0
    trial_add_remaining_days_to_paid: true

    cabinet_enabled: "{{ true if vpn_server_remnawave_tgbot_bedolaga_cabinet_settings | length > 0 else false }}"
    cabinet_jwt_secret: "{{ vpn_server_remnawave_tgbot_bedolaga_cabinet_settings[0].cabinet_jwt_secret }}"
    cabinet_allowed_origins: >-
      {{
        [
          domains_keys.remnawave_tgbot_bedolaga_cabinet
        ]
        if domains_keys.remnawave_tgbot_bedolaga_cabinet is defined
        else []
      }}
