---
- name: Add users based on local file contents
  hosts: all
  become: true
  vars:
    ansible_user: root
  vars_files:
    - "{{ inventory_dir }}/vars/vars.yaml"

  tasks:
    - name: Load user data from a local file
      set_fact:
        user_lines: "{{ lookup('file', '{{ inventory_dir }}/assets/general-machine-prepare/users/users.txt').split(' ') }}"

    - name: Parse user data
      set_fact:
        users: "{{ user_lines |
          map('split', ':') |
          map('list') |
          json_query('[*].{name: [0], state: [1], role: [2]}') }}"

    - name: Add or remove user based on state
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: "{{ 'present' if item.state == 'present' else 'absent' }}"
      loop: "{{ users }}"

    - name: Add user to sudoers if role is super
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
        state: present
      loop: "{{ users }}"
      when: "'super' in item.role"
