---
- name: Install and configure RClone
  hosts: backup_restic_node
  become: false
  become_user: "{{ standard_user }}"
  environment:
    RCLONE_CONFIG_PASS: "{{ rclone_password | default(omit) }}"

  roles:
    - install_backup_node_rclone
