---
- name: Install and configure an Autorestic backup
  hosts: backup_restic_node
  become: false
  become_user: "{{ standard_user }}"

  roles:
    - name: kwtoolset/resolve_host_relations
      vars:
        resolve_host_relations_group: backup_restic_server
        resolve_host_relations_component: autorestic
    - install_backup_node_restic