---
# tasks file for roles/configure_bash_profile
- name: Set context for source file location
  ansible.builtin.set_fact:
    configure_bash_profile_source_file_location: "{{ configure_bash_profile_source_file_location | default('local') }}"

- name: Read full content from file
  ansible.builtin.slurp:
    src: "{{ configure_bash_profile_source_file_path }}"
  register: slurped_file_content

- name: Set fact for source file content from file
  ansible.builtin.set_fact:
    configure_bash_profile_source_file_content: "{{ (slurped_file_content.content | b64decode) | default('') }}"

- name: Ensure destination file exists on target machine
  ansible.builtin.file:
    path: "{{ configure_bash_profile_dest_file_path }}"
    state: touch
    mode: "{{ configure_bash_profile_dest_file_path_mode | default('0644') }}"
  when:
    - configure_bash_profile_source_file_content is defined
    - configure_bash_profile_source_file_content != ''
  ignore_errors: true

- name: Remove legacy unmanaged block
  ansible.builtin.include_tasks: remove_section.yml

- name: Remove regex matches from destination file (if any)
  ansible.builtin.replace:
    path: "{{ configure_bash_profile_dest_file_path }}"
    regexp: "{{ item }}"
    replace: ""
    backup: "{{ configure_bash_profile_backup | default(false) }}"
  with_items: "{{ configure_bash_profile_remove_lines_regex | default([]) }}"
  when:
    - configure_bash_profile_remove_lines_regex is defined
    - configure_bash_profile_remove_lines_regex != []
    - item != ''

- name: Append content from configure_bash_profile_append_lines if defined
  ansible.builtin.set_fact:
    configure_bash_profile_source_file_content: >-
      {{ (
          (configure_bash_profile_source_file_content | default(''))
          +
          (
            (configure_bash_profile_append_lines | join('\n')) 
            if (configure_bash_profile_append_lines is iterable) 
            else (configure_bash_profile_append_lines | default(''))
          )
        ) | default('') }}
  when: configure_bash_profile_append_lines is defined

- name: Ensure full content block is present in destination
  ansible.builtin.blockinfile:
    path: "{{ configure_bash_profile_dest_file_path }}"
    block: "{{ configure_bash_profile_source_file_content | default('') }}"
    append_newline: true
    prepend_newline: true
    marker: "{{ bash_profile_marker }}"
  when:
    - configure_bash_profile_source_file_content is defined
    - configure_bash_profile_source_file_content != ''
  ignore_errors: true
