---
# tasks file for roles/configure_bash_profile
- name: Capture this role's path so nested role can use the parent role_path
  ansible.builtin.set_fact:
    this_role_path: "{{ role_path }}"

- name: Add to source_paths the current role templates directory
  ansible.builtin.set_fact:
    source_paths: >-
      {{
        (
            source_paths_add_role_dirs
            | default([])
            | map('regex_replace', '^(.*)$', this_role_path ~ '/\1/')
            | list
          )
        + (source_paths_add_repo_dirs | default([]))
        + (source_paths_add_user_dirs | default([]))
      }}

- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: _bash_profile
  register: bash_profile_temp_dir
- name: Template bash profile files to temporary directory
  ansible.builtin.template:
    src: "{{ item }}/{{ bash_profile_filename }}"
    dest: "{{ bash_profile_temp_dir.path }}/.bashrc"
  with_items: "{{ source_paths }}"
  failed_when: false

- name: Apply text_from_file role
  ansible.builtin.include_role:
    name: ./roles/kwtoolset/text_from_file
  vars:
    text_from_file_source_file_path: "{{ bash_profile_temp_dir.path }}/.bashrc"
    text_from_file_dest_file_path: "{{ dest_path_root }}/.bashrc"
    text_from_file_dest_file_path_mode: "0644"
    text_from_file_remove_blocks:
      - "{{ bash_profile_marker_legacy }}"
    text_from_file_remove_specific_lines_regex:
      - "alias\\sbr(\\s)?="
    text_from_file_append_lines:
      - "eval \"$(oh-my-posh init bash --config {{ ohmyposh_themes_dir }}/{{ ohmyposh_theme.bash | default(ohmyposh_theme.default) }}.omp.json)\""

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ bash_profile_temp_dir.path }}"
    state: absent