- name: Get compose project safely
  block:
    - name: Get compose project
      ansible.builtin.include_role:
        name: kwtoolset/get_compose_project
      vars:
        get_compose_project_dir: "{{ item }}"
  rescue:
    - name: Show an error if no result
      ansible.builtin.debug:
        msg: "Could not get compose project name for project at {{ item }}. It could be the missing docker-compose.yml file or project directory. Skipping."

- name: Docker Compose project - container pull
  community.docker.docker_compose_v2_pull:
    project_src: "{{ item }}"
    project_name: "{{ get_compose_project_name }}"
    files:
      - docker-compose.yml
  when: get_compose_project_name is defined
  failed_when: false

- name: Docker Compose project - container up
  community.docker.docker_compose_v2:
    project_src: "{{ item }}"
    project_name: "{{ get_compose_project_name }}"
    files:
      - docker-compose.yml
    state: present
  when: get_compose_project_name is defined
  failed_when: false

- name: Prune unused Docker images
  community.docker.docker_prune:
    containers: true
    images: true
    networks: true
    volumes: true
    builder_cache: true
  failed_when: false
  when: item.prune_unused | default(false)