- name: Set cron job name for {{ cron_job_name }}
  set_fact:
    cronjob_base_script: "{{ dest_path_full }}/scripts/rotate.sh"
    cronjob_base_script_with_analytics: "{{ cronjob_base_script }}"
  tags:
    - update_cron_job

- name: Set cron job name for {{ cron_job_name }} - update analytics fact
  set_fact:
    cronjob_base_script_with_analytics: "{{ cronjob_base_script }}"
  tags:
    - update_cron_job

- name: Change cron job path to monitoring if it is in analytics_node group
  set_fact:
    cronjob_script_path_with_analytics: "{{ cron_job_role_prefix }}{{ cron_wrapped_task_prefix }} --job-name '{{ cron_job_name_prefix }}{{ cron_job_name }}' -- {{ cronjob_base_script }} {{ cron_wrapped_task_suffix }}{{ cron_job_role_suffix }}"
  when: "'analytics_node' in group_names"
  tags:
    - update_cron_job

- name: Add cron job for autorestic
  become: true
  become_user: root
  ansible.builtin.cron:
    name: "{{ cron_job_name_prefix }}{{ cron_job_name }}"
    minute: "0"
    hour: "0"
    job: "{{ cronjob_script_path_with_analytics }}"
  tags:
    - update_cron_job

- name: Empty facts
  set_fact:
    cron_job_name: ""
    cronjob_base_script: ""
    cronjob_script_path_with_analytics: ""
  tags:
    - update_cron_job