---
# handlers file for roles/dns_stack
- name: manage dnscrypt when using socket activation
  listen: restart dnscrypt
  when: dnscrypt.use_socket_activation | default(true)
  block:
    - name: restart dnscrypt socket
      ansible.builtin.systemd:
        name: dnscrypt-proxy.socket
        state: restarted
        daemon_reload: true
    - name: disable service unit
      ansible.builtin.systemd:
        name: dnscrypt-proxy.service
        enabled: false
        state: stopped
      ignore_errors: true

- name: manage dnscrypt when using service unit
  listen: restart dnscrypt (service mode)
  when: not (dnscrypt.use_socket_activation | default(true))
  block:
    - name: restart dnscrypt service
      ansible.builtin.systemd:
        name: dnscrypt-proxy
        state: restarted
        daemon_reload: true
    - name: disable socket unit
      ansible.builtin.systemd:
        name: dnscrypt-proxy.socket
        enabled: false
        state: stopped
      ignore_errors: true

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: refresh docker dns
  when: dnscrypt.refresh_docker_dns | default(false)
  ansible.builtin.shell: |
    systemctl reload docker || systemctl restart docker
