# The commented vars should be set in host_vars or in playbook

node_exporter_system_group: node-exp
node_exporter_system_user: node-exp
node_exporter_binary_install_dir: /usr/local/bin
# node_exporter_basic_auth_users:
#   username: password
#   username2: password2
node_exporter_tls_server_config:
  cert_file: "{{ cert_location_root_path }}/{{ domains_keys.node_exporter | default(domains[0]) }}/fullchain.pem"
  key_file: "{{ cert_location_root_path }}/{{ domains_keys.node_exporter | default(domains[0]) }}/privkey.pem"
node_exporter_http_server_config:
  http2: true
node_exporter_web_telemetry_path: /node_exporter_metrics
node_exporter_web_listen_address_host: 0.0.0.0
node_exporter_web_listen_address_port: 49876
node_exporter_web_listen_address: "{{ node_exporter_web_listen_address_host }}:{{ node_exporter_web_listen_address_port }}"

# Append node_exporter_system_user to cert_access_group_users
cert_access_group_users: "{{ ((cert_access_group_users_initial | default([])) + ([node_exporter_system_user | default()])) | unique }}"