# The commented vars should be set in host_vars or in playbook

node_exporter_system_group: node-exp
node_exporter_system_user: node-exp
node_exporter_binary_install_dir: /usr/local/bin
node_exporter_tls_server_config:
  cert_file: "{{ cert_location_root_path }}/{{ cert_location_path_section.main_crt }}"
  key_file: "{{ cert_location_root_path }}/{{ cert_location_path_section.main_key }}"
node_exporter_http_server_config:
  http2: true
node_exporter_web_telemetry_path: /node_exporter_metrics
node_exporter_web_listen_address_host: 0.0.0.0
node_exporter_web_listen_address_port: 49876
node_exporter_web_listen_address: "{{ node_exporter_web_listen_address_host }}:{{ node_exporter_web_listen_address_port }}"
