# The commented vars should be set in host_vars or in playbook

node_exporter_system_group: node-exp
node_exporter_system_user: node-exp
node_exporter_binary_install_dir: /usr/local/bin
node_exporter_web_telemetry_path: /metrics
node_exporter_web_listen_address_host: 172.17.0.1
node_exporter_web_listen_address_port: 9100
node_exporter_web_listen_address: "{{ node_exporter_web_listen_address_host }}:{{ node_exporter_web_listen_address_port }}"
