# There are all possible domains listed, not everything will be used.
# Set of domains depends on group host will be mentioned in.
# They are set there for other groups to be able for inital substitution purposes.
# You should reinitialize them in host_vars/host_name/1_domains.yaml
domains_keys:
  main: sub.example.tld
  prometheus: sub-prometheus.example.tld
  grafana: sub-grafana.example.tld
  victoriametrics: sub-victoriametrics.example.tld
  victorialogs: sub-victorialogs.example.tld
  pushgateway: sub-pushgateway.example.tld
domains: "{{ domains_keys.values() | list | unique }}"