---
# tasks file for roles/add_keys
- name: Add keys to each user
  ansible.builtin.include_tasks: process.yml
  loop: "{{ users_to_set }}"
  loop_control:
    loop_var: user
  when: user.state != 'absent'
