---
# tasks file for roles/install_packages
- name: Install Apt packages
  ignore_errors: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop: "{{ packages_list }}"

- name: Install Snap packages
  ignore_errors: true
  community.general.snap:
    name:
      - procs
