vpn_server_remnawave_tg_bot_instance_count: 1
vpn_server_remnawave_tgbot_jolymmiels_settings:
  - name: ""
    bot_token: <123456789:ABC-DEF1234ghIkl-zyx57W2v1u123ew11> # Telegram bot token that you create in https://t.me/BotFather

    pricing:
      fiat:
        rub:
          months_1: 199
          months_3: 399
          months_6: 899
          months_12: 1499
      crypto:
      tg_stars:
        months_1: 110
        months_3: 230
        months_6: 499
        months_12: 830

    tg_stars_enabled: false

    crypto_enabled: false
    crypto_token: <tg_bot_jolymmiels_crypto_token>
    crypto_pay_url: https://pay.crypt.bot

    yookassa_enabled: false
    yookassa_token: <tg_bot_jolymmiels_yookassa_token>
    yookassa_shop_id: <tg_bot_jolymmiels_yookassa_shop_id>
    yookassa_pay_url: https://api.yookassa.ru/v3
    yookassa_email: <Your Yookassa email>

    tribute_enabled: false
    tribute_webhook: /api/webhook/tribute
    tribute_api_key: <tg_bot_jolymmiels_tribute_api_key>
    tribute_payment_url: <https://t.me/tribute/app?startapp=id>

    referral_days: 7

    miniapp_url: <https://sub.example.tld>

    remnawave_url: <https://sub.example.tld>
    remnawave_api_token: <tg_bot_jolymmiels_api_token>
    caddy_with_auth_api_token: <tg_bot_jolymmiels_api_token>

    trial_traffic_limit: 20
    trial_days: 3
    paid_traffic_limit: 200

    admin_telegram_id: <123456789>

    status_url: <https://sub.example.tld/status>
    support_url: <https://sub.example.tld/support>
    feedback_url: <https://sub.example.tld/feedback>
    channel_url: <https://t.me/examplechannel>


