vpn_server_remnawave_tg_miniapp_api_token: <tg_miniapp_api_token>
vpn_server_remnawave_tg_miniapp_buy_link: <tg://user?id=ID or https://t.me/username>
vpn_server_remnawave_tg_miniapp_x_api_key: <caddy with security api key>