---
version: "3.8"

services:
  xui:
    image: alireza7/x-ui
    container_name: x-ui
    hostname: ${XUI_HOSTNAME}
    volumes:
      - type: bind
        source: ./bin/config.json
        target: /app/bin/config.json
    env_file:
      - .env
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: "${DOMAIN}"
      caddy.0_import: "logging ${DOMAIN}"
      caddy.1_import: "cors"

networks:
  caddy:
    external: true