# If you are using a proxy server to expose some of host ports the Internet, set the following vars
cadvisor_tls_server_config: {} # Remove SSL because there is no need to SSL if some ports are proxied
cadvisor_proxy_server_list:
  - hostname: sub-frps.example.tld              # Domain with FRP server
    url_port: 443                               # Port of FRP server defined in config
    url_path: "/{{ path_to_internal_services_predefined_full }}/frps/proxy/web/22013/metrics"   # Path to access the node_exporter metrics from Internet (by Prometheus)
  - hostname: sub-frps.example.tld
    url_port: 443
    url_path: "/{{ path_to_internal_services_predefined_full }}/frps/proxy/web/22014/metrics"
  - hostname: sub-frps.example.tld
    url_port: 443
    url_path: "/{{ path_to_internal_services_predefined_full }}/frps/proxy/web/22015/metrics"
