version: '3.8'

services:
  wg:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg
    volumes:
      - etc_wireguard:/etc/wireguard
    networks:
      - caddy
    ports:
      - "${WG_PORT}:51920/udp"
      - "${PORT}:51821/tcp"
    restart: unless-stopped
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      caddy: "${DOMAIN}"
      caddy.import: "logging ${DOMAIN}"
      caddy.0_reverse_proxy: "{{ upstreams ${PORT}}}"

networks:
  caddy:
    external: true

volumes:
  etc_wireguard:
