---
# tasks file for roles/install_eget_inherelab

- name: Run check_eget.yml to determine if eget is installed and if it is the inherelab fork
  ansible.builtin.include_tasks: check_eget.yml

- name: Copy eget installation script to /tmp/
  ansible.builtin.copy:
    src: files/scripts/install.sh
    dest: /tmp/eget.sh
    mode: "0755"
  when: eget_installed.rc != 0 or eget_installed_inherelab == false

- name: Run eget.sh to install eget
  ansible.builtin.shell:
    cmd: "timeout {{ eget_inherelab_timeout_seconds }}s /tmp/eget.sh"
  environment:
    NO_COLOR: "1"
  register: eget_install_script_result
  when: eget_installed.rc != 0 or eget_installed_inherelab == false

- name: Check if eget binary exists in user directory
  ansible.builtin.stat:
    path: "{{ eget_location_user_dir }}"
  register: eget_user_dir_stat

- name: Move eget binary to {{ eget_location_bin }}
  become: true
  become_user: root
  ansible.builtin.command: "mv -f {{ eget_location_user_dir }} {{ eget_location_bin }}/"
  when: eget_user_dir_stat.stat.exists

- name: Run check_eget.yml again
  ansible.builtin.include_tasks: check_eget.yml
  when:
    - eget_install_script_result is not skipped
    - eget_install_script_result is succeeded
    - eget_install_script_result.rc == 0

- name: Run eget to update itself
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: "timeout {{ eget_inherelab_timeout_seconds }}s eget update inherelab/eget"
    chdir: "/home/{{ standard_user }}"
  environment:
    NO_COLOR: "1"
  register: eget_update_result
  failed_when: false
  when:
    - eget_installed is not skipped
    - eget_installed is succeeded
    - eget_installed.rc == 0
    - eget_installed_inherelab

- name: Assert that eget update was successful
  ansible.builtin.assert:
    that:
      - eget_update_result is not skipped
      - eget_update_result is succeeded
      - eget_update_result.rc == 0
      - "'Extracted' in eget_update_result.stdout"
      - "'to eget' in eget_update_result.stdout"
    fail_msg: "eget update failed to satisfy conditions with rc: {{ eget_update_result.rc }}"
  when:
    - eget_installed is not skipped
    - eget_installed is succeeded
    - eget_installed.rc == 0
    - eget_installed_inherelab
    - eget_update_result is not skipped
    - eget_update_result is succeeded
    - eget_update_result is defined
    - eget_update_result.rc == 0
    - eget_update_result.stdout is defined

- name: Display latest 3 lines of eget update output for debugging
  ansible.builtin.debug:
    msg: "{{ eget_update_result.stdout_lines[-3:] }}"
  when:
    - eget_installed is not skipped
    - eget_installed is succeeded
    - eget_installed.rc == 0
    - eget_installed_inherelab
    - eget_update_result is not skipped
    - eget_update_result is succeeded
    - eget_update_result is defined
    - eget_update_result.rc == 0
    - eget_update_result.stdout_lines is defined

- name: Install if eget update fails
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: "timeout {{ eget_inherelab_timeout_seconds }}s eget install inherelab/eget"
    chdir: "/home/{{ standard_user }}"
  environment:
    NO_COLOR: "1"
  register: eget_install_result
  when:
    - eget_installed is not skipped
    - eget_installed is succeeded
    - eget_installed.rc == 0
    - eget_installed_inherelab
    - eget_update_result is not skipped
    - eget_update_result.rc == 1
    - eget_update_result.stderr is defined
    - "'use install first' in eget_update_result.stderr"

- name: Assert that eget install was successful
  ansible.builtin.assert:
    that:
      - eget_install_result.rc == 0
      - "'Extracted' in eget_install_result.stdout"
      - "'to eget' in eget_install_result.stdout"
    fail_msg: "eget install failed to satisfy conditions with rc: {{ eget_install_result.rc }}"
  when:
    - eget_installed is not skipped
    - eget_installed is succeeded
    - eget_installed.rc == 0
    - eget_install_result is not skipped
    - eget_install_result is succeeded
    - eget_install_result is defined
    - eget_install_result.rc == 0
    - eget_install_result.stdout is defined

- name: Display latest 3 lines of eget install output for debugging
  ansible.builtin.debug:
    msg: "{{ eget_install_result.stdout_lines[-3:] }}"
  when:
    - eget_installed is not skipped
    - eget_installed is succeeded
    - eget_installed.rc == 0
    - eget_install_result is not skipped
    - eget_install_result is succeeded
    - eget_install_result is defined
    - eget_install_result.rc == 0
    - eget_install_result.stdout_lines is defined

- name: Remove eget.sh from /tmp/
  ansible.builtin.file:
    path: /tmp/eget.sh
    state: absent

- name: Remove eget binary file in user directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ eget_location_user_dir }}"
    state: absent
