---
# tasks file for roles/install_eget_inherelab

- name: Check if eget is already installed
  ansible.builtin.command: which eget
  register: eget_installed
  failed_when: false

- name: Copy eget installation script to /tmp/
  ansible.builtin.copy:
    src: files/scripts/install.sh
    dest: /tmp/eget.sh
    mode: "0755"
  when: eget_installed.rc != 0

- name: Run eget.sh to install eget
  ansible.builtin.command: "bash /tmp/eget.sh"
  when: eget_installed.rc != 0

- name: Run eget to update itself
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: eget update inherelab/eget 2>&1
    chdir: "/home/{{ standard_user }}"
  register: eget_update_result
  when: eget_installed.rc == 0

- name: Clean ANSI escape codes from eget update output
  ansible.builtin.set_fact:
    eget_update_result_cleaned: >-
      {{
        eget_update_result.stdout_lines
        | map('regex_replace', '\x1B\[[0-9;]*[A-Za-z]', '')
        | list
      }}
  when: eget_installed.rc == 0

- name: Assert that eget update was successful
  ansible.builtin.assert:
    that:
      - eget_update_result.rc == 0
      - "'Extracted' in (eget_update_result_cleaned | join('\n'))"
      - "'to eget' in (eget_update_result_cleaned | join('\n'))"
    fail_msg: "eget update failed to satisfy conditions with rc: {{ eget_update_result.rc }}"
  when: eget_installed.rc == 0

- name: Display latest 3 lines of eget update output for debugging
  ansible.builtin.debug:
    msg: "{{ eget_update_result_cleaned[-3:] }}"
  when: eget_installed.rc == 0

- name: Check if eget binary exists in user directory
  ansible.builtin.stat:
    path: "{{ eget_location_user_dir }}"
  register: eget_user_dir_stat

- name: Move eget binary to {{ eget_location_bin }}
  become: true
  become_user: root
  ansible.builtin.command: "mv -f {{ eget_location_user_dir }} {{ eget_location_bin }}/"
  when: eget_user_dir_stat.stat.exists

- name: Remove eget.sh from /tmp/
  ansible.builtin.file:
    path: /tmp/eget.sh
    state: absent
  when: eget_installed.rc != 0

- name: Remove eget binary file in user directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ eget_location_user_dir }}"
    state: absent
