---
- name: Install WireGuard (Easy) with Docker
  hosts: all
  become: true
  vars_files:
    - '{{ inventory_dir }}/vars/vars.yaml'
  vars:
    wg_dir: wireguard

  tasks:
  # Validate fiels and folders exist
  - name: Ensure ~/wg directory exists
    file:
      path: "/home/{{ standard_user }}/{{ wg_dir }}/"
      state: directory
      mode: '0775'
  # Stop and down if it was up
  - name: Check status of Docker Compose services
    command: docker compose ps
    args:
      chdir: "/home/{{ standard_user }}/{{ wg_dir }}/"
    register: docker_compose_status
    ignore_errors: yes
  - name: Stop WireGuard (Easy) service service because it is running
    command: docker compose down wg
    args:
      chdir: "/home/{{ standard_user }}/{{ wg_dir }}/"
    when: "'wg' in docker_compose_status.stdout"
    ignore_errors: yes
  - name: Pull new WireGuard (Easy) release service if it was running
    command: docker compose pull wg
    args:
      chdir: "/home/{{ standard_user }}/{{ wg_dir }}/"
    when: "'wg' in docker_compose_status.stdout"
    ignore_errors: yes
  # Copy files
  - name: Copy all files from local root assets/wireguard to remote ~/wg
    copy:
      src: "{{ inventory_dir }}/assets/wireguard/{{ item.sourcename }}"
      dest: "/home/{{ standard_user }}/{{ wg_dir }}/{{ item.destname }}"
    loop:
      - sourcename: "docker-compose.yml"
        destname: "docker-compose.yml"
      - sourcename: ".env-{{ inventory_hostname }}"
        destname: ".env"
  # Run the service
  - name: Run docker compose up for wg
    command: docker compose up wg -d
    args:
      chdir: "/home/{{ standard_user }}/{{ wg_dir }}/"
    register: docker_compose_up
  - name: Wait for 3 seconds after starting docker compose
    pause:
      seconds: 3
    when: docker_compose_up.changed
  - name: Check if wg service is running correctly
    command: docker compose ps wg
    args:
      chdir: "/home/{{ standard_user }}/{{ wg_dir }}/"
    register: docker_ps
    failed_when: "'Up' not in docker_ps.stdout"
    when: docker_compose_up.changed
