---
- name: Install X-UI with Docker
  hosts: all
  become: true
  become_user: "{{ standard_user }}"
  vars_files:
    - '{{ inventory_dir }}/vars/vars.yaml'
  vars:
    xui_dir: xui

  tasks:
  # Validate fiels and folders exist
  - name: Ensure ~/xui directory exists
    file:
      path: "/home/{{ standard_user }}/{{ xui_dir }}/"
      state: directory
      mode: '0775'
  - name: Ensure ~/xui/db directory exists
    file:
      path: "/home/{{ standard_user }}/{{ xui_dir }}/db"
      state: directory
      mode: '0775'
  # Stop and down if it was up
  - name: Check status of Docker Compose services
    command: docker compose ps
    args:
      chdir: "/home/{{ standard_user }}/{{ xui_dir }}/"
    register: docker_compose_status
    ignore_errors: yes
  - name: Stop X-UI service if it is running
    command: docker compose down xui
    args:
      chdir: "/home/{{ standard_user }}/{{ xui_dir }}/"
    when: "'xui' in docker_compose_status.stdout"
    ignore_errors: yes
  - name: Pull new X-UI release service if it was running
    command: docker compose pull xui
    args:
      chdir: "/home/{{ standard_user }}/{{ xui_dir }}/"
    when: "'xui' in docker_compose_status.stdout"
    ignore_errors: yes
  # Check files existing
  - name: Check if ~/xui/db/ exists
    stat: path="/home/{{ standard_user }}/{{ xui_dir }}/db/x-ui.db"
    register: db_file
  # Copy files
  - name: Copy all files from local root assets/xui to remote ~/xui
    copy:
      src: "{{ inventory_dir }}/assets/xui/{{ item.sourcename }}"
      dest: "/home/{{ standard_user }}/{{ xui_dir }}/{{ item.destname }}"
    loop:
      - sourcename: "docker-compose.yml"
        destname: "docker-compose.yml"
      - sourcename: ".env-{{ inventory_hostname }}"
        destname: ".env"
    register: copy_files_root
  - name: Copy all database files from local root assets/xui/db/ to remote ~/xui/db/
    copy:
      src: "{{ item }}"
      dest: "/home/{{ standard_user }}/{{ xui_dir }}/db/{{ item | basename }}"
    with_fileglob:
      - "{{ inventory_dir }}/assets/xui/db/x-ui.db"
    when: not db_file.stat.exists
    register: copy_files_db
  # Network existing check
  - name: Ensure Docker network 'caddy' exists with specific settings
    docker_network:
      name: caddy
      driver: bridge
      state: present
  # Up the service
  - name: Run docker compose up for X-UI
    command: docker compose up xui -d
    args:
      chdir: "/home/{{ standard_user }}/{{ xui_dir }}/"
    register: docker_compose_up
  - name: Wait for 3 seconds after starting docker compose
    pause:
      seconds: 3
    when: docker_compose_up.changed
  - name: Check if X-UI service is running correctly
    command: docker compose ps xui
    args:
      chdir: "/home/{{ standard_user }}/{{ xui_dir }}/"
    register: docker_ps
    failed_when: "'Up' not in docker_ps.stdout"
    when: docker_compose_up.changed
