---
- name: Install XRay with Docker
  hosts: all
  become: true
  become_user: "{{ standard_user }}"
  vars_files:
    - '{{ inventory_dir }}/vars/vars.yaml'
  vars:
    vpn_dir: vpn
    project_dir: xray
    source_asset_fullpath: "{{ inventory_dir }}/assets/{{ vpn_dir }}/{{ project_dir }}"
    dest_project_fullpath: "/home/{{ standard_user }}/{{ vpn_dir }}/{{ project_dir }}"

  tasks:
  # Validate fiels and folders exist
  - name: Ensure ~/project directory exists
    file:
      path: "{{ dest_project_fullpath }}/"
      state: directory
      mode: '0775'
  - name: Ensure ~/project/config directory exists
    file:
      path: "{{ dest_project_fullpath }}/config"
      state: directory
      mode: '0775'
  # Stop and down if it was up
  - name: Check status of Docker Compose services
    command: docker compose ps
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: docker_compose_status
    ignore_errors: yes
  - name: Stop XRay service if it is running
    command: docker compose down xray
    args:
      chdir: "{{ dest_project_fullpath }}/"
    when: "'xray' in docker_compose_status.stdout"
    ignore_errors: yes
  - name: Pull new XRay release service if it was running
    command: docker compose pull xray
    args:
      chdir: "{{ dest_project_fullpath }}/"
    when: "'xray' in docker_compose_status.stdout"
    ignore_errors: yes
  # Copy files
  - name: Copy all files from local root assets/xray to remote ~/project
    copy:
      src: "{{ source_asset_fullpath }}/{{ item.sourcename }}"
      dest: "{{ dest_project_fullpath }}/{{ item.destname }}"
    loop:
      - sourcename: "docker-compose.yml"
        destname: "docker-compose.yml"
      - sourcename: ".env-{{ inventory_hostname }}"
        destname: ".env"
    register: copy_files_root
  - name: Copy all files from local root assets/xray/config/ to remote ~/project/config/
    copy:
      src: "{{ item }}"
      dest: "{{ dest_project_fullpath }}/config/{{ item | basename }}"
    with_fileglob:
      - "{{ source_asset_fullpath }}/config/config.json"
    register: copy_files_config
  # Network existing check
  - name: Ensure Docker network 'caddy' exists with specific settings
    docker_network:
      name: caddy
      driver: bridge
      state: present
  # Up the service
  - name: Run docker compose up for XRay
    command: docker compose up xray -d
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: docker_compose_up
  - name: Wait for 3 seconds after starting docker compose
    pause:
      seconds: 3
    when: docker_compose_up.changed
  - name: Check if XRay service is running correctly
    command: docker compose ps xray
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: docker_ps
    failed_when: "'Up' not in docker_ps.stdout"
    when: docker_compose_up.changed
