---
- name: Install FRP with Docker
  hosts: all
  become: true
  become_user: "{{ standard_user }}"
  vars_files:
    - '{{ inventory_dir }}/vars/vars.yaml'
  vars:
    vpn_dir: vpn
    project_dir: frp
    source_asset_fullpath: "{{ inventory_dir }}/assets/{{ vpn_dir }}/{{ project_dir }}"
    dest_project_fullpath: "/home/{{ standard_user }}/{{ vpn_dir }}/{{ project_dir }}"

  tasks:
  # Validate fiels and folders exist
  - name: Ensure ~/project directory exists
    file:
      path: "{{ dest_project_fullpath }}/"
      state: directory
      mode: '0775'
  - name: Ensure ~/project/config-frpc directory exists
    file:
      path: "{{ dest_project_fullpath }}/config-frpc"
      state: directory
      mode: '0775'
  - name: Ensure ~/project/config-frps directory exists
    file:
      path: "{{ dest_project_fullpath }}/config-frps"
      state: directory
      mode: '0775'
  # Stop and down if it was up
  - name: Check status of Docker Compose services
    command: docker compose ps
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: docker_compose_status
    ignore_errors: yes
  - name: Stop FRP service service because it is running
    command: docker compose down frps
    args:
      chdir: "{{ dest_project_fullpath }}/"
    when: "'frps' in docker_compose_status.stdout"
    ignore_errors: yes
  - name: Stop FRP client service because it is running
    command: docker compose down frpc
    args:
      chdir: "{{ dest_project_fullpath }}/"
    when: "'frpc' in docker_compose_status.stdout"
    ignore_errors: yes
  - name: Pull new FRPS release service if it was running
    command: docker compose pull frps
    args:
      chdir: "{{ dest_project_fullpath }}/"
    when: "'frps' in docker_compose_status.stdout"
    ignore_errors: yes
  - name: Pull new FRPC release service if it was running
    command: docker compose pull frpc
    args:
      chdir: "{{ dest_project_fullpath }}/"
    when: "'frpc' in docker_compose_status.stdout"
    ignore_errors: yes
  # Copy files
  - name: Copy all files from local root assets/frp to remote ~/project
    copy:
      src: "{{ source_asset_fullpath }}/{{ item.sourcename }}"
      dest: "{{ dest_project_fullpath }}/{{ item.destname }}"
    loop:
      - sourcename: "docker-compose.yml"
        destname: "docker-compose.yml"
      - sourcename: ".env-{{ inventory_hostname }}"
        destname: ".env"
  - name: Copy FRPC config from local assets/frp/config-frpc to remote ~/project/config-frpc
    copy:
      src: "{{ item }}"
      dest: "{{ dest_project_fullpath }}/config-frpc/{{ item | basename }}"
    with_fileglob:
      - "{{ source_asset_fullpath }}/config-frpc/*"
    register: copy_files_frpc_config
  - name: Copy FRPS config from local assets/frp/config-frps to remote ~/project/config-frps
    copy:
      src: "{{ item }}"
      dest: "{{ dest_project_fullpath }}/config-frps/{{ item | basename }}"
    with_fileglob:
      - "{{ source_asset_fullpath }}/config-frps/*"
    register: copy_files_frpc_config
  # Create backups for .env file
  - name: Copy FRPS config file to backup
    ansible.builtin.copy:
      src: "{{ dest_project_fullpath }}/.env"
      dest: "{{ dest_project_fullpath }}/.env.bak"
      remote_src: true
  # Remove comments, empty line and trailing spaces from .env file
  - name: Remove comments, empty line and trailing spaces from .env file
    command: sed -i -e 's/[[:space:]]*#.*//' -e 's/[[:space:]]*$//' -e '/^$/d' .env
    args:
      chdir: "{{ dest_project_fullpath }}/"
  # Substitute variables from .env file in FRP config files
  - name: Substitute variables in FRPS config file
    command: docker container run --rm -it --env-file .env -v .:/wd bhgedigital/envsubst sh -c "envsubst < /wd/config-frps/frps.toml.template > /wd/config-frps/frps.toml" && cat config-frps/frps.toml
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: envsubst_frps
  - name: Substitute variables in FRPC config file
    command: docker container run --rm -it --env-file .env -v .:/wd bhgedigital/envsubst sh -c "envsubst < /wd/config-frpc/frpc.toml.template > /wd/config-frpc/frpc.toml" && cat config-frpc/frpc.toml
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: envsubst_frpc
  # Run the service
  - name: Run docker compose up for frps
    command: docker compose up frps -d
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: docker_compose_up
  - name: Wait for 3 seconds after starting docker compose
    pause:
      seconds: 3
    when: docker_compose_up.changed
  - name: Check if frps service is running correctly
    command: docker compose ps frps
    args:
      chdir: "{{ dest_project_fullpath }}/"
    register: docker_ps
    failed_when: "'Up' not in docker_ps.stdout"
    when: docker_compose_up.changed
