---
- name: Generate the passwords the secret templates use
  ansible.builtin.include_role:
    name: setup/common
    tasks_from: generate_passwords
  vars:
    setup_generate_passwords: "{{ setup_secrets_generated_passwords }}"
    setup_generate_passwords_length: "{{ setup_secrets_password_length }}"
    setup_generate_passwords_special_chars: "{{ setup_secrets_password_special_chars }}"
