vector_exporter_server_users:
  - name: username
    password: <password>
    hash_scheme: bcrypt

victorialogs_endpoints:
  - url: <url to victorialogs server>
    username: <username>
    password: <password>

vector_sinks:
  sinks:
    prometheus_sink:
      inputs:
        - host_metrics_source # you can change this name in vector.yaml.j2
      type: prometheus_pushgateway
      endpoint: <url to prometheus server starting from https://> # e.g. https://<prometheus_compatible_sink_url>/api/v1/write, like PushGateway
      auth:
        strategy: basic
        user: <prometheus_user>
        password: <prometheus_password>
      healthcheck:
        enabled: false

    victorialogs_sink:
      inputs:
        - journald_source # you can change this name in vector.yaml.j2
        - parse_logs_containers # you can change this name in vector.yaml.j2
      type: elasticsearch
      endpoints:
        - <url to victorialogs server starting from https://> # e.g. https://<victorialogs_url>/insert/elasticsearch/
      auth:
        strategy: basic
        user: <victorialogs_user>
        password: <victorialogs_password>
      mode: bulk
      api_version: v8
      healthcheck:
        enabled: false
      query:
        _msg_field: message
        _time_field: timestamp
        _stream_fields: host,container_name
