---
analytics_node_project_structure_end_dirs__host:
  caddy_exporter: "{{ analytics_node_project_structure_root }}/caddy_exporter"
  docker_exporter: "{{ analytics_node_project_structure_root }}/docker_exporter"
  frps_exporter: "{{ analytics_node_project_structure_root }}/frps_exporter"
  node_exporter: "{{ analytics_node_project_structure_root }}/node_exporter"
  fail2ban_exporter: "{{ analytics_node_project_structure_root }}/fail2ban_exporter"
  pushgateway: "{{ analytics_node_project_structure_root }}/pushgateway"
  cadvisor: "{{ analytics_node_project_structure_root }}/cadvisor"
  vector_exporter: "{{ analytics_node_project_structure_root }}/vector"
  wg_exporter: "{{ analytics_node_project_structure_root }}/wg_exporter"
  any_subdirectory_name: "{{ analytics_node_project_structure_root }}/any_subdirectory_name"

analytics_node_project_structure_end_dirs: >-
  {{
    lookup('community.general.merge_variables',
           '^analytics_node_project_structure_end_dirs__.*',
           wantlist=True
          )
    | combine({}, recursive=False)
  }}

analytics_node_project_structure_end_dirs_list: "{{ analytics_node_project_structure_end_dirs.values() | list }}"
