---
# tasks file for roles/install_eza
- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download and dearmor the GPG key
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    dest: /tmp/deb.asc
    mode: "0644"

- name: Convert the GPG key to gpg format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/gierens.gpg /tmp/deb.asc
    creates: /etc/apt/keyrings/gierens.gpg

- name: Add Gierens repository to sources list
  ansible.builtin.copy:
    content: "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main\n"
    dest: /etc/apt/sources.list.d/gierens.list
    mode: "0644"

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install eza package
  ansible.builtin.apt:
    name: eza
    state: present
