---
# tasks file for roles/install_eza
  - name: Ensure /etc/apt/keyrings directory exists
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Download and dearmor the GPG key
    get_url:
      url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
      dest: /tmp/deb.asc
      mode: '0644'

  - name: Convert the GPG key to gpg format
    command:
      cmd: gpg --dearmor -o /etc/apt/keyrings/gierens.gpg /tmp/deb.asc
      creates: /etc/apt/keyrings/gierens.gpg

  - name: Add Gierens repository to sources list
    copy:
      content: "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main\n"
      dest: /etc/apt/sources.list.d/gierens.list
      mode: '0644'

  - name: Update apt package index
    apt:
      update_cache: yes

  - name: Install eza package
    apt:
      name: eza
      state: present
