# This file contents should be put in example_for_vpn_xui_first.yaml or example_for_vpn.yaml
# Data that should be replaced is in <angle brackets>

prometheus:
  domain: "{{ domains_keys.prometheus }}"
  port: 9090
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_configs:
    - job_name: <JOB NAME>
      static_configs:
        - targets: ["<sub.example.tld:someport>"]
      basic_auth:
        username: <someuser>
        password: <somepass>
      scheme: https
      metrics_path: /<your_metrics_path> # The `/` slash is important
      tls_config:
        insecure_skip_verify: true
      # Relabeling "instance" to remove the ":9100" part
      relabel_configs:
        - source_labels: [__address__]
          target_label: instance
          regex: '([^:]+)(:[0-9]+)?'
          replacement: '${1}'
  basic_auth_users:
    <someuser1>: <bcrypt_hashed_password>
    <someuser2>: <bcrypt_hashed_password>
  tls_server_config:
    cert_file: "/etc/ssl/{{ domains_keys.prometheus }}/{{ domains_keys.prometheus }}.crt"
    key_file: "/etc/ssl/{{ domains_keys.prometheus }}/{{ domains_keys.prometheus }}.key"
  remote_write_list:
    - url: <sub.example.tld:someport/somepath> # Usually your Grafana endpoint credentials
      basic_auth:
        username: <someuser>
        password: <somepass>
      queue_config:
        capacity: 5000
        max_shards: 200
        min_shards: 1
        max_samples_per_send: 10000
        batch_send_deadline: 5s
        min_backoff: 30ms
        max_backoff: 100ms