---
# tasks file for roles/install_bash_profile
- name: Read aliases from local .bashrc file
  ansible.builtin.set_fact:
    aliases_content: "{{ lookup('file', bash_asset_fullpath + '/.bashrc', errors='ignore').splitlines() }}"
  failed_when: aliases_content == ['']
  ignore_errors: true

- name: Ensure .bashrc exists on target machine
  ansible.builtin.file:
    path: "/home/{{ standard_user }}/.bashrc"
    state: touch
    mode: "0644"
  when:
    - aliases_content is defined
    - aliases_content != ['']
  ignore_errors: true

- name: Add aliases to .bashrc if not present
  ansible.builtin.lineinfile:
    path: "/home/{{ standard_user }}/.bashrc"
    line: "{{ item }}"
    state: present
    create: true
    insertafter: EOF
  with_items: "{{ aliases_content }}"
  when:
    - item != ''
    - aliases_content is defined
    - aliases_content != ['']
  ignore_errors: true
