---
# tasks file for roles/install_vpn_caddy_tblocker

- name: Capture this role's path so nested role can use the parent role_path
  ansible.builtin.set_fact:
    this_role_path: "{{ role_path }}"
  tags:
    - always

- name: Add to source_paths the current role templates directory
  ansible.builtin.set_fact:
    source_paths: >-
      {{
        (
            source_paths_add_role_dirs
            | default([])
            | map('regex_replace', '^(.*)$', this_role_path ~ '/\1/')
            | list
          )
        + (source_paths_add_repo_dirs | default([]))
        + (source_paths_add_user_dirs | default([]))
      }}
  tags:
    - always

- name: "Extract binary package info"
  ansible.builtin.set_fact:
    binary_pkg: "{{ packages_binary_list
                   | selectattr('repo','search','xray-torrent-blocker')
                   | list
                   | first }}"
  tags:
    - never
    - update_image
    - update_executable
- name: "Install binary using eget"
  ansible.builtin.include_role:
    name: ./roles/install_packages_binary
    apply:
      tags:
        - never
        - update_image
        - update_executable
  vars:
    packages_binary_list:
      - "{{ binary_pkg }}"
  args:
    apply:
      become: true
      become_user: root
  tags:
    - never
    - update_image
    - update_executable

- name: copy_files_templating
  ansible.builtin.include_role:
    name: kwtoolset/copy_files_templating
    apply:
      tags:
        - update_config
  vars:
    copy_files_templating_dir_list:
      - src: "{{ source_path }}/templates/config"
        dest: "{{ dest_path_full }}"
        default_mode: "0775"
  with_items: "{{ source_paths }}"
  loop_control:
    loop_var: source_path
  tags:
    - update_config

- name: Copy config for tblocker systemd service
  ansible.builtin.template:
    src: "{{ this_role_path }}/templates/systemd/tblocker.service.j2"
    dest: "{{ dest_path_full_systemd }}/tblocker.service"
  tags:
    - update_config
- name: Enable and start tblocker service
  ansible.builtin.systemd:
    name: tblocker
    enabled: true
    state: started
    daemon_reload: true
  register: tblocker_service_status
  failed_when: tblocker_service_status is failed
  tags:
    - update_config
    - update_image
    - update_executable