---
# tasks file for roles/vpn_xui_first_xui_configure

- name: Template the {{ configuredb_file_name }}.sql.j2 file on the destination machine
  ansible.builtin.template:
    src: "{{ source_asset_fullpath_common }}/db/{{ configuredb_file_name }}.sql.j2"
    dest: "{{ dest_project_fullpath }}/db/{{ configuredb_file_name }}.sql"
  when:
    - configuredb_file_name is defined
    - configuredb_file_name != ""
- name: Execute SQL file on SQLite database
  ansible.builtin.shell:
    cmd: "sqlite3 {{ dest_project_fullpath }}/db/x-ui.db < {{ dest_project_fullpath }}/db/{{ configuredb_file_name }}.sql"
  when:
    - configuredb_file_name is defined
    - configuredb_file_name != ""

- name: Process each of base file names
  ansible.builtin.include_tasks: process.yaml
  loop: "{{ base_file_names }}"
  loop_control:
    loop_var: item
