# You can define additional DNS records to be set for this host, in addition to the records defined by the domains_keys variable.
# In entries of this structure, there could be any of the same keys as in the community.general.cloudflare_dns role
# If value prop is absent, it means role fills it with the host's ansible_host (IPv4 address for A record).
# All others (except dns_provider and state) are mapped as is
# dns_records_addition:
#   - name: "{{ domains_keys.main }}"
#     type: A
#     ttl: 300
#     dns_provider: cloudflare
#   - name: "{{ domains_keys.remna_node[0].domain }}"
#     type: A
#     ttl: 300
#     value: "{{ ansible_host }}" # there can be, or cannot, a value for this record, depending on user
#     dns_provider: cloudflare

# You can also define the DNS records explicitly, instead of using the domains_keys variable. It will override the records defined by the domains_keys variable.
# In entries of this structure, there could be any of the same keys as in the community.general.cloudflare_dns role
# If value prop is absent, it means role fills it with the host's ansible_host (IPv4 address for A record).
# All others (except dns_provider and state) are mapped as is
# dns_records_override:
#   - name: "{{ domains_keys.main }}"
#     type: A
#     ttl: 300
#     value: "{{ ansible_host }}" # there can be, or cannot, a value for this record, depending on user
#     dns_provider: cloudflare
#   - name: "{{ domains_keys.remna_node[0].domain }}"
#     type: A
#     ttl: 300
#     dns_provider: cloudflare
