# The commented vars should be set in host_vars or in playbook
# The `restic_node_vars` is an example of how to configure restic
# You should set this var, too, in host_vars or in playbook

restic_node_cron_job_name: "Autorestic backup"
restic_node_cron_job_name_forget: "Autorestic forget"
restic_node_cron_job_name_prefix: "/bin/bash -c 'sleep $((RANDOM\\%300))' &&"
restic_excludes_list_files:
  - excludes-common.txt
  - excludes-dev-build.txt
  - excludes-dev-code.txt
  - excludes-home-dirs.txt
  - excludes-root.txt

restic_global_forget:
  keep-last: 5
  keep-daily: 4
  keep-weekly: 1
  keep-monthly: 12
  keep-yearly: 7
