---
# tasks file for roles/install_backup_node_postgres
- name: Capture this role's path so nested role can use the parent role_path
  ansible.builtin.set_fact:
    this_role_path: "{{ role_path }}"
  tags:
    - always

- name: Add to source_paths the current role templates directory
  ansible.builtin.set_fact:
    source_paths: >-
      {{
        (
            source_paths_add_role_dirs
            | default([])
            | map('regex_replace', '^(.*)$', this_role_path ~ '/\1/')
            | list
          )
        + (source_paths_add_repo_dirs | default([]))
        + (source_paths_add_user_dirs | default([]))
      }}
  tags:
    - always

- name: "Create non-existent parent directories for {{ dest_path_full }}"
  ansible.builtin.include_role:
    name: ./roles/kwtoolset/create_dirs_traversal
    apply:
      tags:
        - update_config
  vars:
    create_dirs_traversal_path: "{{ dest_path_full }}"
    create_dirs_traversal_strip_leaf: true
    create_dirs_force_mode: "0775"
  tags:
    - update_config

# GROUP, SSL DIRECTORY AND PERMISSIONS
- name: Create {{ pgdump_backup_access_group }} group
  become: true
  become_user: root
  ansible.builtin.group:
    name: "{{ pgdump_backup_access_group }}"
    state: present

- name: Add users to {{ pgdump_backup_access_group }} group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ pgdump_backup_access_group }}"
    append: true
  with_items: "{{ pgdump_backup_access_group_users }}"

- name: Ensure that pgdump_backup_location_root_path exists
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ pgdump_backup_location_root_path }}"
    state: directory
    owner: "{{ pgdump_backup_location_root_owner }}"
    group: "{{ pgdump_backup_access_group }}"
    mode: "{{ pgdump_backup_location_root_permissions }}"

- name: Set fact for location types
  ansible.builtin.set_fact:
    static_backup_locations: "{{ backup_locations
      | selectattr('type','defined')
      | selectattr('type','equalto','static')
      | list }}"
    dynamic_backup_locations: "{{ backup_locations
      | selectattr('type','defined')
      | selectattr('type','equalto','dynamic_list')
      | list }}"
    expanded_dynamic_backup_locations: []

- name: Expand each dynamic backup location
  ansible.builtin.include_tasks: expand-dynamic.yml
  loop: "{{ dynamic_backup_locations }}"
  loop_control:
    loop_var: dynamic_location

- name: Deploy all backup locations
  ansible.builtin.include_tasks: process-static.yml
  loop: "{{ static_backup_locations + expanded_dynamic_backup_locations }}"
  loop_control:
    loop_var: location

