---
# tasks file for roles/install_backup_node_postgres
- name: Capture this role's path so nested role can use the parent role_path
  ansible.builtin.set_fact:
    this_role_path: "{{ role_path }}"

- name: Add to source_paths the current role templates directory
  ansible.builtin.set_fact:
    source_paths: >-
      {{
        (
            source_paths_add_role_dirs
            | default([])
            | map('regex_replace', '^(.*)$', this_role_path ~ '/\1/')
            | list
          )
        + (source_paths_add_repo_dirs | default([]))
        + (source_paths_add_user_dirs | default([]))
      }}

# GROUP, SSL DIRECTORY AND PERMISSIONS
- name: Create {{ pgdump_backup_access_group }} group
  become: true
  become_user: root
  ansible.builtin.group:
    name: "{{ pgdump_backup_access_group }}"
    state: present

- name: Add users to {{ pgdump_backup_access_group }} group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ pgdump_backup_access_group }}"
    append: true
  with_items: "{{ pgdump_backup_access_group_users }}"

- name: Ensure that pgdump_backup_location_root_path exists
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ pgdump_backup_location_root_path }}"
    state: directory
    owner: "{{ pgdump_backup_location_root_owner }}"
    group: "{{ pgdump_backup_access_group }}"
    mode: "{{ pgdump_backup_location_root_permissions }}"

- name: copy_files_templating
  ansible.builtin.include_role:
    name: kwtoolset/copy_files_templating
  vars:
    copy_files_templating_dir_list:
      - src: "{{ source_path }}"
        dest: "{{ dest_path_full }}"
        default_mode: "0775"
  with_items: "{{ source_paths }}"
  loop_control:
    loop_var: source_path

# Cron job
- name: Change cron job path to monitoring if it is in analytics_node group
  set_fact:
    cronjob_script_path_with_analytics: "{{ pgdump_backup_cron_job_name_prefix}} {{ cron_wrapped_task_prefix }} --job-name postgres_backup -- {{ cronjob_script_path_without_analytics }} {{ cron_wrapped_task_suffix }} {{ pgdump_backup_cron_job_name_suffix }}"
  when: "'analytics_node' in group_names"

# RUN SCRIPTS AND SET
- name: Run backup script
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: "./scripts/backup.sh"
    chdir: "{{ dest_path_full }}"
  register: backup_result
- name: Fail if backup script failed
  ansible.builtin.fail:
    msg: "Backup script failed with error: {{ backup_result.stderr }}"
  when: "'Error' in backup_result.stderr"
- name: Add cron job for pgdump (not in analytics_node group)
  become: true
  become_user: root
  ansible.builtin.cron:
    name: "{{ pgdump_backup_cron_job_name }}"
    minute: 0
    hour: 0
    job: "{{ cronjob_script_path_without_analytics }}"
  when: "'analytics_node' not in group_names"
- name: Add cron job for pgdump (analytics_node group)
  become: true
  become_user: root
  ansible.builtin.cron:
    name: "{{ pgdump_backup_cron_job_name }}"
    minute: 0
    hour: 0
    job: "{{ cronjob_script_path_with_analytics }}"
  when: "'analytics_node' in group_names"
