---
# tasks file for roles/install_eget
- name: Check if eget is already installed
  ansible.builtin.command: which eget
  register: eget_installed
  ignore_errors: true

- name: Download eget installation script to /tmp/
  ansible.builtin.get_url:
    url: https://zyedidia.github.io/eget.sh
    dest: /tmp/eget.sh
    mode: "0755"
  when: eget_installed.rc != 0

- name: Run eget.sh to install eget
  ansible.builtin.command: "bash /tmp/eget.sh"
  when: eget_installed.rc != 0

- name: Run eget to update itself
  ansible.builtin.command: eget zyedidia/eget
  when: eget_installed.rc == 0

- name: Move eget binary to {{ eget_location_bin }}
  ansible.builtin.command: "mv ./eget {{ eget_location_bin }}/"
  args:
    creates: "{{ eget_location_bin }}/eget"

- name: Remove eget.sh from /tmp/
  ansible.builtin.file:
    path: /tmp/eget.sh
    state: absent

- name: Remove eget binary file in user directory
  ansible.builtin.file:
    path: "{{ eget_location_user_dir }}"
    state: absent
