- name: Set fact for restic_node_vars.locations and restic_node_vars.remotes
  ansible.builtin.set_fact:
    restic_node_vars:
      locations: >-
        {{ backup_restic_node_locations_base
           | combine(backup_restic_node_locations_additional|default({}), recursive=True) }}
      remotes: >-
        {{ backup_restic_node_remotes_base
           | combine(backup_restic_node_remotes_additional|default({}), recursive=True) }}
